### ISSUE TITLE
Unexpected behaviour in similar templates

### ISSUE THREAD

**Issue by vetcher** [CloudyKit/jet#101]
I'm passing ```{"a":null}``` (decoded to map[string]interface{}) to template
```
{{ .a }}
```
and receiving error `there is no field or method "a" in map[string]interface {}`
When I change template to 
```
{{ .["a"] }}
```
and everything works (as expected).
But, if I pass ```{"a":{"b":null}}``` to templates 1)`{{.a.b}}` and 2)`{{.a["b"]}}` I'm receiving error 1)`there is no field or method "b" in map[string]interface {}` and 2) nothing (everything ok).

As I understand, for data structure `map[string]map[string]map[string]map[string]map[string]interface{}` template 
```
{{ .a.b.c.d.e.f }}
```
would raise error, but for
```
{{ .a.b.c.d.e["f"] }}
```
everything works fine.

So my question is:
Why jet can't select the last element in chain of map[string]interface{} by using dots (not square brackets)?

And can I push pr that fix this?

**Comment by annismckenzie** [comment]
Huh, that looks like a bug. Could you a test? And yes, a PR is much appreciated!

**Comment by vetcher** [comment]
@annismckenzie could you also set patch tag (may be not released)?

**Comment by annismckenzie** [comment]
@vetcher I'll release v2.2.0 later today.
