### ISSUE TITLE
split(key, string) not working as intended?

### ISSUE THREAD

**Issue by JesseRyan** [CloudyKit/jet#105]
```
{{block SplitTest(splitTestString="55 55 55 55")}}
{{ testStringArray := split(" ", splitTestString)}}
{{ testStringArray}}
{{ splitTestString }}
{{ testStringArray[0] }}
{{end}}
```

Trying to reference testStringArray[0] causes gophers to panic.
And splitTestString shows the correct value.
But testStringArray shows: [ ] when I render the template...

Is split a function we can expect to work? Or perhaps my syntax is missing something here?

**Comment by annismckenzie** [comment]
`{{ split("stringToSplit", "separator") }}` – the `split` function only wraps `strings.Split` from the standard library which has the string as the first and the separator as the second argument: https://godoc.org/strings#Split.

Why did you think it was the other way around? Are our docs wrong? 🤔 The wiki page at https://github.com/CloudyKit/jet/wiki/4.-Built-in-functions#from-gos-strings-package specifically mentions `from go's strings package`.

**Comment by JesseRyan** [comment]
You're right, i had initially surmised the go documentation:
```
func Split(s, sep string) []string

Split slices s into all substrings separated by sep and returns a slice of the substrings between those separators.

If s does not contain sep and sep is not empty, Split returns a slice of length 1 whose only element is s.

If sep is empty, Split splits after each UTF-8 sequence. If both s and sep are empty, Split returns an empty slice.

It is equivalent to SplitN with a count of -1. 
```

s to me looked like the key. I will close when I confirm this works.
