### ISSUE TITLE
Custom renderer with jet.Renderer not working

### ISSUE THREAD

**Issue by bboehmke** [CloudyKit/jet#106]
It seams that the custom renderer are not working since the Commit 91ac9cb0201cc9d6b4130277c2f7e4b3685850f6.

I tried the todo example but it did not work until I undo the change of this commit.

I tested it with go 1.11 under Linux amd64.

**Comment by annismckenzie** [comment]
Oh no, that doesn’t sound good. Thanks for the report, I’ll take a look!

**Comment by tooolbox** [comment]
@bboehmke, the commit you referenced has been reverted in v3.0.0--is this still an issue for you, or can we close?

**Comment by bboehmke** [comment]
I quickly checked with the todo example and I thing it is working since 941e482e again.

**Comment by tooolbox** [comment]
Great!  Ready to close, then?
