### ISSUE TITLE
question about extends

### ISSUE THREAD

**Issue by marcelloh** [CloudyKit/jet#113]
When I do an extends like this :
{{extends "/layouts/main.jet"}}
and I have the configuration like this:
views  = jet.NewHTMLSet("./views")
I expect the program to look in the directory views//layouts/ for main.jet, but when I debug, I see is first starts to look for the file in other directories.
I expect to do like that when I omit the first slash like this: 
{{extends "layouts/main.jet"}} because it is not a relative path
when I start with a slash, it's more an absolute path, so this "looking for the file somewhere", could possibly go a little faster. (but perhaps I'm wrong)
What do you think?

**Comment by sauerbraten** [comment]
Sound related to #127.

If you still use jet and care, can you try if https://github.com/sauerbraten/jet/tree/clean-up-tmpl-loading behaves like you expect?

**Comment by tooolbox** [comment]
Sounds confusing.

`/layouts/main.jet` is an absolute path, and `layouts/main.jet` is a relative path.

I think @marcelloh if you want help with this you need to provide more specific information rather than "starts to look for the file in other directories".

**Comment by sauerbraten** [comment]
I think what he's seeing is that `/layouts/main.jet` is looked up inside the directory of the including template first, which makes no sense. It has to do what I described in #127:

- `/layouts/user.jet` has `{{ extends "/layouts/main.jet" }}`
- `resolveNameSibling()` finds a `"/"` in `/layouts/user.jet`
- it will try to load `layouts//layouts/main.jet` (https://github.com/CloudyKit/jet/blob/33cfc27b3e00072655fdb3af24c3253ea5bffb8f/template.go#L157)

> I expect to do like that when I omit the first slash like this:
> {{extends "layouts/main.jet"}} because it is not a relative path

They meant "is not an absolute path" there (or "is a relative path").

`{{ extends "layouts/main.jet" }}` inside `/layouts/user.jet` **should** try `/layouts/layouts/main.jet` (and only that one path), according to every program dealing with paths except for jet.

jet shouldn't attempt to interpret `{{ extends "/layouts/main.jet" }}` as a relative path, which is what I argue in #127 and which I'm pretty sure is what @marcelloh meant.

**Comment by sauerbraten** [comment]
Fixed in #129.
