### ISSUE TITLE
HTML in template vars

### ISSUE THREAD

**Issue by voidhaze** [CloudyKit/jet#115]
Hi guys, we are looking to use Jet in production, we were wondering if there was a way to embed HTML in a template var so that it would render when the variable is printed.

```
{{ testVar := "<h2>HELLO WORLD</h2>"}}

<html>
{{ testVar }}
</html>
```
currently it just prints ```<h2>HELLO WORLD</h2>``` in plain text

**Comment by annismckenzie** [comment]
You'll have to use the `raw` filter – see https://github.com/CloudyKit/jet/wiki/4.-Built-in-functions#escape-helper

So that'd be:
```html
<html>
{{ testVar | raw }}
</html>
```

Please be sure that the HTML is safe (careful with user input) if you do this.

**Comment by voidhaze** [comment]
Cheers!
