### ISSUE TITLE
  How to use for loop in jet template

### ISSUE THREAD

**Issue by wx85278161** [CloudyKit/jet#116]
How to use for loop in jet template?

**Comment by kataras** [comment]
https://github.com/CloudyKit/jet/blob/62edd43e4f88c6be452fd5feac77f716f546ebf6/examples/todos/views/todos/index.jet#L22-L27

**Comment by kataras** [comment]
Although the example doesn't work as expected, try to pass it by value instead: `func(dt doneTODOs) Range` and it will work, the problem lives on its `getRanger` which neither the https://github.com/CloudyKit/jet/pull/112 fixes, instead it makes the pass by value not work too... I'll fix it on the [Iris](https://iris-go.com) Jet view engine [integration](https://github.com/kataras/iris/issues/1281#issuecomment-504521832) but needs a fix on this repository so all users will benefit from it.

**Comment by kataras** [comment]
The same problem is visible on the `Renderer` as well, take for example the todo's example `func (t *tTODO) Render(r *view.JetRuntime) {`. ^

**Comment by tooolbox** [comment]
@kataras I believe #126 should have fixed this, can you comment?
