### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by frederikhors** [CloudyKit/jet#118]
Is this project abandoned?

**Comment by marcelloh** [comment]
why do you ask?

**Comment by frederikhors** [comment]
21 issues and latest commit over one year ago. Can you answer?

**Comment by annismckenzie** [comment]
Sorry for being so quiet. We're still happily using the latest released version in production and have been for the last years. Still, we're moving everything to Vue apps + APIs so we'll retire our app that uses Jet in the near future. I know that there's open issues and also some contributions. I hope we can address those soon.

**Comment by japettyjohn** [comment]
Jet support was also just added to [iris](https://github.com/kataras/iris/) 9 days ago.

While Jet it is not currently the [most popular](https://github.com/topics/template-engine?l=go&o=desc&s=stars) template engine for Go, I'd still argue it still fits as one of the best. Very close to standard library golang templates, doesn't offer so much functionality so as to make your templates a class all their own.

And like @annismckenzie said, it is proven in production.

**Comment by tooolbox** [comment]
@annismckenzie shall we close this?  It's resolved, and it doesn't look good to have your top issue be "Is this project abandoned?"

**Comment by annismckenzie** [comment]
You're right – closing.
