### ISSUE TITLE
Cannot debug vendored jet

### ISSUE THREAD

**Issue by nkev** [CloudyKit/jet#120]
This is on go1.13.1 darwin/amd64
I'm using jet with `go mod` outside of GOPATH and vendored. It compiles and runs fine, but in VS Code if I hit debug (to debug with delve), I get the error:
```
build github.com/nkev/my-app: cannot load github.com/CloudyKit/jet: module github.com/CloudyKit/jet@latest (v2.1.2+incompatible) found, but does not contain package github.com/CloudyKit/jet
```
Any ideas?

**Comment by marcelloh** [comment]
even if you solve it, be polity and tell us what you did, so other people can learn from this too.
