### ISSUE TITLE
OSFileSystemLoader shouldn't manage multiple directories

### ISSUE THREAD

**Issue by sauerbraten** [CloudyKit/jet#128]
Having `OSFileSystemLoader` manage multiple directories can lead to unexpected behavior:
- assume we have
    - `/home/bla/templates/foo/a/b/c.jet`
    - `/home/bla/templates/bar/a/b/c.jet`
- using `NewHTMLSet("/home/bla/templates/foo", "/home/bla/templates/bar")`
- the following is undefined: `{{ include "a/b/c.jet" }}`

Which template is included depends on the order in which you pass the directory paths to `NewHTMLSet`, which is documented nowhere.

**Comment by tooolbox** [comment]
> the following is undefined: `{{ include "a/b/c.jet" }}`

Well, it's not so much undefined but rather it depends on the sequence of your directory paths 😆 

But your point is taken and I think this will make the API more obvious moving forward.

**Comment by sauerbraten** [comment]
Okay, let's say *non-obivous ;)

**Comment by sauerbraten** [comment]
Fixed by https://github.com/CloudyKit/jet/pull/129.
