### ISSUE TITLE
Pass new scope to yield and include

### ISSUE THREAD

**Issue by annismckenzie** [CloudyKit/jet#13]
I'm trying to imitate some of the approaches other frameworks take to provide a common library of reusable parts for forms. The `{{import "form_theme_bootstrap.jet" }}` and the `{{yield}}` directive are good building blocks to achieve that. The problem arrises when trying to pass local variables to use when yielding, for example, an `input-field` block in the sense that it's not possible (at least I don't see a way).

Let me explain with some code:

```HTML
<!-- file: "form_theme_bootstrap.jet" -->
{{block input-field}}
  <div class="{{container_class}} {{if has_error}}invalid{{else}}valid{{end}}">
    <input id="{{name}}" name="{{name}}" value="{{value}}" />
    {{if has_error}}
      <div class="form_error">{{error}}</div>
    {{end}}
  </div>
{{end}}
```

```HTML
<!-- file: "user_form_edit.jet" -->
{{import "form_theme_bootstrap.jet"}}

<form>
  <!-- not sure how passing a hash/map of local variables would work  -->
  {{yield input-field { name: "firstname", value: .Firstname, has_error: errs.HasErrorFor("Firstname"), error: errs.ErrorFor("Firstname"), container_class: "" }  }}
</form>
```

Do you see what I'm trying to do? Having a way to construct a map on the fly in the template would be really great, that way I could use that as the context for the yield.

Thanks again for all the hard work and this great library!

**Comment by jhsx** [comment]
Hi @annismckenzie, this is one good feature, i tried to implement this before but not worked well the way i was doing, that was by providing a map func which builds a map ex: 
```go
map("Key","Value","Key1","Value1") 
```
 and then you can pass the map as a expression for any thing that you want.

The problema with that approach was the fact that map access with reflect is very slow, then we need to avoid to use map and reflect.

I think the best way to add this, is by providing a special syntax to pass a new scope declaration to yield,block and include, the tests that you added in the pull request #12 are good start point, i will start another branch than we can experiment with the syntax.

Thanks

**Comment by annismckenzie** [comment]
I've been thinking about a good way to achieve this.

How about adding a block-form of yield? That would be considerably different from the current yield and would implicitly add the necessary context.

Keeping with my original example:

```HTML
<!-- file: "user_form_edit.jet" -->
{{import "form_theme_bootstrap.jet"}}

<form>
  <!-- not sure how passing a hash/map of local variables would work  -->
  {{ user := users[userId] }} <!-- added this to make it clear where the variable is coming from below -->
  {{yield input-field}}
    {{ name := "firstname" }} <!-- variable declaration like it's now -->
    {{ name, container_class := "firstname", "" }} <!-- second option to shorten templates (just an idea) -->
    {{ value := user.Firstname }}
    {{ has_error := errs.HasErrorFor("Firstname") }}
    {{ container_class := has_error ? "has-error" : "" }} <!-- of course, these kinds of things can also happen in the input-field block -->

    <!-- extra nice for wrapping: add contents here that are passed to the block and can be yielded inside -->
    <p>Some extra text which can be yielded in the input-field block as {{contents}}.</p>
  {{end}}
</form>
```

```HTML
<!-- file: "form_theme_bootstrap.jet" -->
{{block input-field}}
  <div class="{{container_class}} {{if has_error}}invalid{{else}}valid{{end}}">
    <input id="{{name}}" name="{{name}}" value="{{value}}" />
    {{if has_error}}
      <div class="form_error">{{error}}</div>
    {{end}}
  </div>
  {{if isset(contents)}}
    {{contents}}
  {{end}}
{{end}}
```

How would that be performance-wise?

You could capture the variables created as the new context and could even capture the contents into a separate variable, making wrapping possible:

```HTML
  {{block row}}
    <div class="row">{{contents}}</div>
  {{end}}

  {{yield row}}
    <p>A whole lot of contents that will be wrapped.</p>
  {{end}}
```

The result would be:

```HTML
  <div class="row"><p>A whole lot of contents that will be wrapped.</p></div>
```

What do you think?

**Comment by jhsx** [comment]
I've been quite busy those days, so, didn't thought much about that.


About the proposed solution, by providing two kinds of yield we'll make the parser quite more complex, a solution would be adding new keyword.

Ex:
```html
{{yieldContext blockName}} <h1>Content</h1> {{end}}
````

But the most consistent solution would be to allow a declaration in yield,block and include.
Ex: 
```html
{{yield blockName name,value := "name","value"; .Context }}
{{include "template-name.jet" name,value := "name","value"; .Context }}
{{include "template-name.jet" name := "name", value := "value" ; .Context }}
{{include "template-name.jet" name := "name", value := "value" }}
```

**Comment by jhsx** [comment]
Hi @annismckenzie, i came up with one solution for this, the idea is to allow the block statement to have expressions as a  additional parameters ex:
```html
{{ block textfield(label="",name="",value="") }}
  {{label}}: <input type="text" name="{{name}}" value="{{value}}" />
{{end}}
```
the parameters are expressions trees, so, they only will be evaluated inside the block when needed
```html
{{yield textfield(label="Name", name="name",value=.Post("Name")) }}
or
{{yield textfield("Please say your Name", "name", .Post("Name")) }}
{{yield textfield("Please say your Name", value="name") }}
```
another case would be the addition of the content keyword
```
{{block row(cols=12,offset=0)}}
<div class="row col-md-{{cols}}">{{content}}</div>
{{end}}

{{yield row(6) content}}
<div>{{.Data}}</div>
{{end}}
```
What do you think ?

**Comment by annismckenzie** [comment]
Love it!
Especially the more explicit:
```
{{ block textfield(label="",name="",value="") }}
```
and
```
{{yield textfield(label="Name", name="name",value=.Post("Name")) }}
```

That even makes default values possible. This would be awesome to have!

**Comment by jhsx** [comment]
Good to know, thanks for the feedback. 👍

**Comment by annismckenzie** [comment]
Am I correct in assuming that when you say `expression trees` that parsing these only happens once? That is, are these cached when not in development mode?

**Comment by jhsx** [comment]
Yes you're correct.

**Comment by jhsx** [comment]
i detected a problem while working on this, i can not make this compatible with the old syntax, if i continue in this path all block and yield statements would require syntax like of a func call, ex 

```html
{{ block name(defineOne,defineTwo) }}
{{ end }}
 or 
{{ block name() }}
{{ end }}
or
{{ yield name(name,value) .NewContext }}
{{ yield name() .NewContext }}
```

**Comment by annismckenzie** [comment]
Lookin' good! As for the function call syntax change: fine with me. We should update the readme and the wiki (I can do that if you want) and the fix is purely mechanical by searching all template files of a project for `block` and `yield` and adding the parentheses.

Finally, you could publish this on gopkg.in as v1 (or similar) when it's done?

**Comment by jhsx** [comment]
That would be great and if you can test too the new branch, would help a lot. 
Ya, a simple regex can do the job.

The code in new_block branch already works, but we need a lot more tests to catch any possible bug that may have.

About the release, i am thinking in tag this as 2.0 since many things changed and move the project to github.com/go-jet/jet then we can import with gopkg.in/jet.v1 or and gopkg.in/jet.v2.

Then maintain a fork in github.com/CloudyKit/jet for someone that may be using the library.

**Comment by annismckenzie** [comment]
Wow, you're already at the benchmarking stage. I have a few templates that need this new syntax so I'll of course take it for a spin.

I concur with moving the project and also releasing this as a v2. 👍 

Thanks for your hard work!

**Comment by jhsx** [comment]
You're welcome 👍

**Comment by annismckenzie** [comment]
Sorry for the delay – going to switch my project over to the `v2` branch today – will make failing test cases if there are any issues. How do you want me to handle this? I could push them directly into the branch instead of doing the branch-PR dance. Would you upgrade me to a contributor? 😄

**Comment by annismckenzie** [comment]
Just hit a road block.

Suppose I have this defined:
```HTML
<!-- file: "_blocks.jet" -->
{{block title(add_app_prefix=true, prefix="")}}
  <title>{{if add_app_prefix}}Our application name: {{end}}{{prefix}}{{yield content}}</title>
{{end}}
```
There's gonna be other common blocks in there (sub navigation and whatnot). Now, I have an application layout that looks like this:
```HTML
<!-- file: "application.jet", i.e. the application layout -->
{{import "_blocks.jet"}}
<!DOCTYPE html>
<html>
  <head>
    {{yield title()}} <!-- how would I pass the parameters of the block here? -->
  </head>
  <body></body>
</html>
```

In another template I'm now doing this:
```HTML
<!-- file: "some_page.jet" -->
{{extends "application.jet"}}

{{block title()}}the title of this page{{end}} <!-- use default parameters and set the content to yield -->
{{block title(prefix="sub page prefix - ")}}the title of this page{{end}} <!-- set parameter as well as the content to yield -->
...
```

Maybe the cascading title is a suboptimal example because one can't have more than one in the `<head>` but here's what I'd expect to be rendered:

```HTML
<!DOCTYPE html>
<html>
  <head>
    <title>Our application name: the title of this page</title> <!-- first block invocation -->
    <title>Our application name: sub page prefix - the title of this page</title> <!-- second block invocation -->
...
```
Of course that doesn't work because I can't figure out how to pass the parameters the imported block is called with to the yield. Somehow I'm using it backwards, aren't I?

Sorry for the lengthy comment again, I wanted to be as specific as possible.

**Comment by jhsx** [comment]
If you want to pass a content to the yield, then you will need to pass the content keyword at the end of the yield statement.

Ex:
```go
{{yield title(prefix="sub page prefix - ") content}}the title of this page{{end}}
```

**Comment by jhsx** [comment]
I like that there is someone besides me that is interested in contribute to this project. So, i will make a team and add you, but i prefer that we use pull request in that way we can have tests running in the ci and do a quick code review before we merge.

**Comment by jhsx** [comment]
For wiki and other stuff we can update directly

**Comment by annismckenzie** [comment]
This is awwwwwesome, thanks! 👯  👯  👯  Regarding the pull requests: no questions there, that's exactly the way I like to work. 👍

**Comment by annismckenzie** [comment]
Great, this is working with the `content` keyword. I ended up doing this:

```HTML
<!-- file: "application.jet", i.e. the application layout -->
<title>{{yield cascadingTitle()}}</title> <!-- as it's in the layout I can't yield with parameters -->

<!-- file: "some_page.jet" -->
{{extends "application.jet"}}
{{block cascadingTitle()}}
  {{yield title(prefix=user.DisplayName()+" - ") content}}your rooms{{end}}
{{end}}
```

Looks a bit awkward but this really is a special case where I'm yielding at a point where I don't have access to the data I need to pass.

For a simple case like this I really like the new way of assembling strings – super-handy and readable. No more sprintf-ing with awkward format strings (needs some restraint to stay readable, though). 👍

**Comment by jhsx** [comment]
Done.
