### ISSUE TITLE
Release v3

### ISSUE THREAD

**Issue by tooolbox** [CloudyKit/jet#130]
With #121 we added Go Modules support at v3.  This was partly done because of backwards-incompatible changes starting around July 2019 with #97 

However, because some of the PRs accepted during that time period have [caused](https://github.com/CloudyKit/jet/issues/122) [regressions](https://github.com/CloudyKit/jet/issues/123), there have been some [reversions](https://github.com/CloudyKit/jet/pull/126).

In the meantime, there are [new PRs](https://github.com/CloudyKit/jet/pull/129) which, although they are progressive and seem overall positive, will create breaking changes.

As a user of Jet, and of Go Modules, I would like to have a major version of Jet released with Go Modules support that I can stably use without worrying about API changes.  I propose that we tag & release `v3.0.0` as a somewhat "existing Jet with Go Modules support" and can then use `v4.0.0` for any actual breaking changes to the API or behavior.  The branches can be maintained & patched separately, although perhaps some feature adds could be back-ported to v3 and released as minor versions.

cc @annismckenzie @sauerbraten

**Comment by annismckenzie** [comment]
Hey guys, sorry about the silence. Yes, I think this is a very good idea. I'll tag the current master with v3.0.0 as a stop-gap today.

**Comment by tooolbox** [comment]
Looks like we have a v3.0.0 tag now!  🎉

**Comment by annismckenzie** [comment]
Done. I'll update our web app to v3.0.0 and everything will hopefully still work.
