### ISSUE TITLE
Please explain why defining a block causes it to be executed?

### ISSUE THREAD

**Issue by rmzg** [CloudyKit/jet#132]
> Keep in mind that the place where you define a block is also the place where it's invoked (see Define 
> & Invoke Together). If that's not what you want then you have to put it in another template and 
>import it, see Import Statement.```

For the life of me I can't think of a single reason why anyone would want this behaviour and trying to figure out why it was designed like this is driving me slightly mad, can you please give me an explanation?

**Comment by sauerbraten** [comment]
Although I understand your confusion, and wonder myself why jet doesn't have `define` to define a block without executing it, it's most likely because `block` behaves the same in Go's text/template: https://golang.org/pkg/text/template/ (search for 'block')

**Comment by mvrhov** [comment]
It also behaves the same in other non Go template engines. e.g PHP's Twig and Python's Poco.
Both of those languages use macro for what you want to achieve.
