### ISSUE TITLE
howto create map/slice within the template

### ISSUE THREAD

**Issue by Dexus** [CloudyKit/jet#135]
hey,

i have a problem and need to create a map/slice in the template to call some functions after it.

But I can't find a working solution currently.

I run a loop over a DB and would like to generate a link for each entry with different data. 

Any Idea that would help me?

Thx

**Comment by annismckenzie** [comment]
Sorry for the silence. You should prepare the data outside of the template where you have real Go available to you. I really wouldn't do that in a template.
