### ISSUE TITLE
Stepping down as contributor

### ISSUE THREAD

**Issue by annismckenzie** [CloudyKit/jet#146]
Hey guys.

I have bad news. It's been such a long time that I really really really actively participated in any meaningful activities in this project that it's not just embarrassing but also deeply disrespectful to all the people that want bugs to be fixed, features to be added, documentation to be written and generally just have this library move forward with momentum. Lots of issues and MRs are awaiting review or triaging – waiting on me to move them forward.

I'm no longer using Jet in any of my projects – neither at work nor in my spare time and my work has moved on from template engines to managing microservices, heavy DevOps automation and guiding junior software engineers on their path to become senior software engineers.

It's with a heavy heart that I have to step down as a contributor. I'm so sorry. :(

**Comment by razonyang** [comment]
I am sad to hear that, thank you for your long-term contribution.
Does this mean that the project is no longer maintained? Are other members maintaining it?

**Comment by annismckenzie** [comment]
Thanks, that means a lot! I really don't know. I haven't heard from @jhsx in ages. Most recently @sauerbraten was quite active but I don't know how he feels about picking up the mantle.

**Comment by tooolbox** [comment]
Thanks for your stewardship @annismckenzie it shall be missed.

...Yeah, who is running the show then?  👀 

I do use the library so I have a vested interest in compatibility and stability fixes moving forward.  It would be sad to not be able to merge fixes anymore.

**Comment by jhsx** [comment]
@annismckenzie thank you so much for everything you did for this project and sorry for not be much present last year.

I still don't have much time to work in the project, but, in the mean while i will be able to review and merge pull requests and fix bugs, if someone is interested to help mantain the project please step up.

And thanks a lot for every one helping and using this project.

**Comment by razonyang** [comment]
Hi @jhsx, I am using Jet in my projects, I hope I could get involved and help maintain this project in my spare time.

**Comment by annismckenzie** [comment]
Thanks José, that means a lot! ❤️

**Comment by sauerbraten** [comment]
Thanks for all the time and energy you put into jet, @annismckenzie!

The company I work for uses jet heavily, so I/we definitely have an interest in its continuation. I'd be happy to help out in the future with PRs, issues, and docs, provided my work schedule allows it (which lately wasn't the case, so it got a bit quiet from me).

I also think @tooolbox would be a good choice if we're looking for people that can handle contributions. (Maybe he's already able to merge PRs and close issues etc. and I missed that, in which case: sorry!)

**Comment by tooolbox** [comment]
Thanks for the nomination @sauerbraten 😄   I don't have any capabilities, but I wouldn't object; I invested a lot in the Wiki already, and I can usually make some time to handle PRs and issues.

Back at you--seems like you would be a good steward, if you're not already a collaborator on the repo.

**Comment by sauerbraten** [comment]
I think I am a collaborator, at least I can merge PRs and close issues, but I somehow can't find a list of my permissions in this repository. I'll try to be a little more active here in the future, gladly with some help! :)

**Comment by jhsx** [comment]
Hi @sauerbraten thanks for the time you're investing in this project also, your permissions was a writer before and I changed to maintainer now.

I think we can close this issue now.
