### ISSUE TITLE
README clean up

### ISSUE THREAD

**Issue by sauerbraten** [CloudyKit/jet#155]
- remove outdated benchmarks
- remove "upgrade to v2" section

**Comment by sauerbraten** [comment]
- add information about upcoming v4 and breaking changes since v3

**Comment by tooolbox** [comment]
Maybe handle https://github.com/CloudyKit/jet/issues/60 while you're at it :)

(Or just close the ticket if we don't care.)

**Comment by sauerbraten** [comment]
- link to updated docs

**Comment by sauerbraten** [comment]
closed with https://github.com/CloudyKit/jet/commit/2ada4091acbbc7981ee93f5a91c33fdf539ee4c4
