### ISSUE TITLE
Add function capturing syntax

### ISSUE THREAD

**Issue by sauerbraten** [CloudyKit/jet#162]
From https://github.com/CloudyKit/jet/issues/82#issuecomment-653627407:

> would be kinda cool to do something like [Gleam's function capture](https://gleam.run/tour/functions.html#function-capturing) where you can specify what position you want the argument in, so like `{{ foo()|bar(_, param2, param3)|baz(param1, _, param3) }}` (Gleam probably took that from somewhere, but that's just where I've seen it recently.)

cc @tooolbox

**Comment by tooolbox** [comment]
Note that if there's no `_` argument, it defaults to passing the result as the first argument.

...Wonder how this would interact with multiple return values.

**Comment by sauerbraten** [comment]
Yep, that's exactly what makes it compatible with jet's existing syntax! 🙌

I haven't looked into how it would be implemented, but it should work just like calling functions that return multiple values works right now. (Which I don't know, to be honest, and if it works at all.)
