### ISSUE TITLE
Add simple for loop for repeating a block

### ISSUE THREAD

**Issue by pipe01** [CloudyKit/jet#163]
For example:

```
{{repeat i := 1 to 6}}
   ...
{{end}}
```

**Comment by sauerbraten** [comment]
Jet v4 has a built-in ints-Ranger and new one-var range assignment syntax, so you can write `range i := ints(0,6)` now to get `i == 0` to `i == 5`.

I think that's enough and there's no need to add new syntax for this use case.

**Comment by pipe01** [comment]
Yeah that covers it, now I just have to wait for Iris to update to v4. Thank you!
