### ISSUE TITLE
about using content yield

### ISSUE THREAD

**Issue by ryanzl** [CloudyKit/jet#170]
```
{{block navList()  }}
    {{field := "123"}}
    {{yield content}}
{{end}}
```

```
{{yield navList() content}}
    <div>
        {{field}}
     </div>
{{end}}
```

My expected output is as follows：
`<div>123</div>`

**Comment by sauerbraten** [comment]
Can you elaborate? What's the output you see, if it's not what you expect?

**Comment by ryanzl** [comment]
__

> Can you elaborate? What's the output you see, if it's not what you expect?

Sorry, I have reedited the content

**Comment by sauerbraten** [comment]
It is intended behavior that `yield content` restores the variable scope of the `yield block() content` statement. Your `field` variable is defined inside the scope of a `block`, so the outer scope, from which `yield navList() content` starts, doesn't see that var.

Quoting https://github.com/CloudyKit/jet/blob/master/docs/syntax.md#content:
> The invocating yield ({{ yield link(target="https://www.example.com") content }}) will store the content (together with the current variable scope) and the {{ yield content }} part will restore the variable scope and execute the content.

If you look at the example there, you see that this would work in your case:

```
{{ field := "123" }}
{{ block navList()  }}
    {{ yield content }}
{{ end }}

{{ yield navList() content }}
    <div>
        {{ field }}
     </div>
{{ end }}
```

That is, you have to declare and set `field` outside of the block, so it's visible when you yield the block using `yield navList() content`.
