### ISSUE TITLE
Create v3 branch

### ISSUE THREAD

**Issue by tooolbox** [CloudyKit/jet#175]
I have a [bugfix](https://github.com/CloudyKit/jet/compare/v3.0.0...tooolbox:20200905-v3.0.1?expand=1) I'd like to land and release as v3.0.1.

@sauerbraten would you mind making a branch for v3 so I can open a PR against it?  Thanks.

**Comment by sauerbraten** [comment]
Sure, no problem, here you go: [support/v3](https://github.com/CloudyKit/jet/tree/support/v3)

Thanks for the fix in advance!

**Comment by sauerbraten** [comment]
By the way, you fix seems to be backporting #148, maybe mention that one in your PR for future reference :)
