### ISSUE TITLE
Whitespace trimming problem

### ISSUE THREAD

**Issue by kaibox-git** [CloudyKit/jet#177]
If I place the only string:
start {{- "abc" -}} end
to remove whitespaces and get "startabcend" I get error:
Jet Runtime Error("page.jet":1): template: header.jet:1: unexpected token "}}" on operand

Gennerally, I want to remove all "spaces, horizontal tabs, carriage returns, and newlines" between html tags in the source page. Is there a simple way to do it?

**Comment by sauerbraten** [comment]
There's no support for whitespace control from inside templates like Go's [text/template package](https://golang.org/pkg/text/template/) supports. It's on the to-do list! If you want, feel free to try and open a PR!

**Comment by kaibox-git** [comment]
No support?... What about this feature https://github.com/CloudyKit/jet/blob/master/docs/syntax.md#whitespace-trimming ?

**Comment by sauerbraten** [comment]
Good point, I forgot we merged that feature. We didn't release it yet, which is why it doesn't work for you despite the docs mentioning it. I'll publish 5.1.0 right now so you can update!

**Comment by sauerbraten** [comment]
Here we go: https://github.com/CloudyKit/jet/releases/tag/v5.1.0

 Let me know if you still run into problems by reopening this issue!

**Comment by kaibox-git** [comment]
Works, many thanks!
