### ISSUE TITLE
Thread safe jet.Template

### ISSUE THREAD

**Issue by Dynom** [CloudyKit/jet#181]
In line of my previous Issue https://github.com/CloudyKit/jet/issues/180 I've considered of re-using instances of `jet.Template` as much as possible. However I'm pretty sure that in their current form they are not safe for concurrent use:
```go
func (t *Template) ExecuteI18N(translator Translator, w io.Writer, variables VarMap, data interface{}) (err error) {
	st := pool_State.Get().(*Runtime)
	defer st.recover(&err)

	st.blocks = t.processedBlocks // <-- Unsafely copying a Map
	st.translator = translator
	st.variables = variables
	st.set = t.set                // <-- Unsafely referencing *Set, copying over at least Set.globals and Set.escapee
	st.Writer = w

	// resolve extended template
	for t.extends != nil {
		t = t.extends         // <-- Unsafely mutating `t`
	}

	if data != nil {
		st.context = reflect.ValueOf(data)
	}

	st.executeList(t.Root)        // <-- st.executeList() unsafely accesses t.Root.Nodes
	return
}
```

A test to show data races, when run as: `go test -race -test.run ^TestJetConcurrency$`
```go
// jetversion5 "github.com/CloudyKit/jet/v5"
func TestJetConcurrency(t *testing.T) {
	views := jetversion5.NewHTMLSet(".")
	tpl, err := views.LoadTemplate("foo", "{{if true}}Hi {{- .Name -}}!{{end}}")
	if err != nil {
		t.Errorf("Error in test %s", err)
	}

	for i := 0; i < 3; i++ {
		t.Run(fmt.Sprintf("CC_%d", i), func(t *testing.T) {
			t.Parallel()

			err = tpl.Execute(ioutil.Discard, nil, struct{ Name string }{Name: "John"})
			if err != nil {
				t.Errorf("Error in test %s", err)
			}
		})
	}
}
```

Version: v5.1.1

**Comment by sauerbraten** [comment]
- `st.blocks = t.processedBlocks` is okay as long as the template is not re-parsed while it is executed, which I'm pretty sure is impossible from outside the jet package and isn't done inside the package.
- `st.set = t.set` only copies a pointer to the Set, nothing inside it
- `t = t.extends` also only sets a local copy of the `tpl` pointer inside your t.Run() to a new value
- `st.executeList(t.Root)` is (like accessing `t.processedBlock`) okay as long as the template is not re-parsed during execution

The data race you see in your test actually stems from all your goroutines writing to the same `err` variable. If you use `err := tpl.Execute(...)` the data race warning should be gone.

I'll see if we have to do more to ensure parsing and execution of a template don't interfere, but really I believe there is nothing stopping you from concurrently executing an already parsed template. It's something we do all the time.

**Comment by sauerbraten** [comment]
I added concurrency tests in #183, in https://github.com/CloudyKit/jet/pull/183/files#diff-25a0667bae3252b54c2ab9b135a9f45619dbca8a953cc7e727a921bc7ed49294 and https://github.com/CloudyKit/jet/pull/183/files#diff-8a66b04ca105f4c888fe120c4ff874111f38c62b5752c4de61db5d1521a8200e to be exact. I consider this issue closed, since it wasn't broken to begin with and is now regression-tested.

**Comment by Dynom** [comment]
Thanks! And you are absolutely right, in the current form there isn't a problem with concurrency. Thanks for your work on Jet!
