### ISSUE TITLE
error render: template index does not exist

### ISSUE THREAD

**Issue by cyanBone** [CloudyKit/jet#184]
engine := jet.New("./views", ".jet.html")

return ctx.Render("index", fiber.Map{
			"Title": "Hello, World!",
		})

file :
views/index.jet.html

error render: template index does not exist

**Comment by sauerbraten** [comment]
It looks like you're not using the latest version of Jet, and also use Jet inside a framework?

For me, this setup works fine: [jet_issue_184.zip](https://github.com/CloudyKit/jet/files/5589263/jet_issue_184.zip)
