### ISSUE TITLE
How to implement a GlobalFunc with n-arguments

### ISSUE THREAD

**Issue by wsantos** [CloudyKit/jet#192]
Hi I've been playing with this template system and I'm enjoying using it, but I'm not sure how to properly implement a Global function for the reverse function on Echo, I'd appreciate some example, at this moment I'm looping through the arguments creating a list and passing to the reverse function, but I'm not sure this is the correct way 

This is how I did, still not sure if this is the correct way, tho.

```go
	t.Templates.AddGlobalFunc("reverse", func(a jet.Arguments) reflect.Value {
		a.RequireNumOfArguments("revese", 1, -1)

		args := make([]interface{}, a.NumOfArguments())
		for i := 1; i < a.NumOfArguments(); i++ {
			args[i-1] = a.Get(i)
		}

		return reflect.ValueOf(c.Echo().Reverse(a.Get(0).String(), args...))
	})
```

**Comment by jhsx** [comment]
Hi @wsantos, that's how you do.

**Comment by wsantos** [comment]
Thank you.
