### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by aspacca** [CloudyKit/jet#203]
Hello,

we are evaluating adopting jet as template engine in https://github.com/elastic/elastic-integration-corpus-generator-tool and we would like to understand the status of the project.

Until few days ago there were no new commits since March 2021.
What is the current status?

cc @sauerbraten, @matheusd

**Comment by matheusd** [comment]
I'm just a (very recent) user and eventual contributor, not a maintainer, but jet seemed like most performant one from the ones I evaluated (apart from ones using generated code). It was also simple enough that I could benchmark hotspots of the current version and address them as needed.

**Comment by tooolbox** [comment]
IMO it's fairly feature-complete and doesn't need a lot of commits.  But there does seem to be a maintainer who accepts PRs.

**Comment by sauerbraten** [comment]
I was working on this at my previous job, and haven't really been using it for a year now. I don't have the time to fix bugs myself to be honest, but I'll look through well-written, tested PRs.
I'm also open to pass the torch to someone more invested in this project of course.

I'm unsure even if the owning organization is still using jet? 🤔 @annismckenzie, @jhsx

**Comment by annismckenzie** [comment]
I haven't used Jet in over 3 years and I stepped down as a contributor/maintainer in #146. :/

**Comment by aspacca** [comment]
thank you everyone for the feedback :)
