### ISSUE TITLE
String based componentization

### ISSUE THREAD

**Issue by e200** [CloudyKit/jet#207]
Im wondering if it would be possible to have string based componentization. This would allow a very flexible loading of the components (also allowing the use of different storages like S3, Databases, etc...) directly without relying solely in a tree of files in the file system. 

It would be something like this:

```golang
jet.SetComponent("component-name", content)
```

Where content is **[]byte** and it's source can be anything, anywhere!

Does it make sense for you? It would help us a lot migrating from handlebars to this library, which I think would be awesome!

**Comment by marcelloh** [comment]
This is what I do:
```
	vars := jet.VarMap{}
	vars.Set("component-name"", content)
```

**Comment by e200** [comment]
Hi @marcelloh, thank you for the ideia. Is your code or Jet able to resolve a var as a component? Can I call **@yield component-name** where component name is the var you just added and the var content be rendered? Thank you.

**Comment by marcelloh** [comment]
I think, what you want is doable. In your case, it is a slice of bytes, right?
Well you can do that in fields as well.
``` fields map[string]any ```

Let me show my example:
```
/*
Title makes a title version of the string.
*/
func Title(text string) string {
	caser := cases.Title(language.Und, cases.NoLower)
	text = caser.String(text)

	return strings.TrimSpace(text)
}
```
and then, somewhere in your code:
```
	vars := jet.VarMap{}
	vars.Set("Title", plugin.Title)
```
so in this case it's a function.
Now you can call this function in your template:
```
 {{ Title("my title") }}
```
But you can put anything in it.

**Comment by e200** [comment]
Ok, I think I got you. That's exactly what I was looking for and it seems workable. Thank you for showing me the way 🙂

**Comment by sauerbraten** [comment]
Make sure to also check out [the Loader interface](https://beta.pkg.go.dev/github.com/CloudyKit/jet/v6#Loader) and e.g. [its httpfs implementation](https://beta.pkg.go.dev/github.com/CloudyKit/jet/v6@v6.2.0/loaders/httpfs). That might be an easier solution for your use case (S3).

**Comment by e200** [comment]
> Make sure to also check out [the Loader interface](https://beta.pkg.go.dev/github.com/CloudyKit/jet/v6#Loader) and e.g. [its httpfs implementation](https://beta.pkg.go.dev/github.com/CloudyKit/jet/v6@v6.2.0/loaders/httpfs). That might be an easier solution for your use case (S3).

This is even better 🔥

Thank you very much for your suggestions.
