### ISSUE TITLE
From NewHTMLSet to NewSet

### ISSUE THREAD

**Issue by marcelloh** [CloudyKit/jet#208]
I used this:
```
	 views = jet.NewHTMLSet(
	 	rootDir+"/templates/common",
	 	rootDir+"/templates/",
	 	rootDir+"/rendering/templates/",
	 )
```
But wonder how adding mutliple locations looks like with NewSet()
I have this, but can add only 1 location:
```
		views = jet.NewSet(
			jet.NewOSFileSystemLoader(rootDir+"/rendering/templates/"),
			jet.InDevelopmentMode(), // remove in production
		)
```
Any hints are welcome :-)

**Comment by sauerbraten** [comment]
Use a multi loader (https://pkg.go.dev/github.com/CloudyKit/jet/v6@v6.2.0/loaders/multi) around multiple OSFileSystemLoaders.
