### ISSUE TITLE
Add a special func type that can be called directly without the overhead of reflect.Call

### ISSUE THREAD

**Issue by jhsx** [CloudyKit/jet#21]
Adding this will give ability for users to create fast functions, and with this we can remove the len builtin, and implement trans as a default func.

ex: 
```go
set.AddGlobal("len",func(a JetArguments) reflect.Value {
       a.RequireNumOfArguments(1,1)
       slice := a.GetKind(0,reflect.Slice,reflect.Array,reflect.Map,reflect.String)
       return reflect.Value(slice.Len())
})
```

**Comment by annismckenzie** [comment]
Can you explain what's necessary to implement these `fast functions`? Looked at the implementation of `len` and `isset` but don't really understand it.

**Comment by jhsx** [comment]
these fast functions can be implemented by implementing jet.Func type, this special type will eliminate the need to use reflect.Call which has a bit of overhead.

**Comment by jhsx** [comment]
functions implementing this type can be at least 2x times faster than the same func being called by reflect.Call

**Comment by annismckenzie** [comment]
That sounds very good. Is that something developers using Jet while building web apps would do every once in a while? Would be something for the advanced topics chapter in the wiki.

**Comment by jhsx** [comment]
This would be a good to do if you have a function that is called multiple times in your template, per example, a function which generates urls, normal function we can stick with dynamic call through reflect.Call.
