### ISSUE TITLE
v6 doesn't always recognise the rangeable interface

### ISSUE THREAD

**Issue by prantlf** [CloudyKit/jet#220]
I upgraded from `github.com/CloudyKit/jet` to `github.com/CloudyKit/jet/v6` and enumerating the map ranges in some templates started failing. The custom `jet.Ranger` interface wasn't recognised any more. I tried to create a minimal repo demonstrating the problem: https://github.com/prantlf/jetnoranger. It contains two executables to demonstrate the problem. This is their output:

Succesful one depending on `github.com/CloudyKit/jet`:

    ❯ ./success/success
      Key Name:
        Scalar: Barbarian
      Key Description:
        Scalar: A fierce warrior of primitive background who can enter a battle rage
      Key Proficiencies:
          Key Armor:
            Array: [Light armor Medium armor Shields]
          Key Weapons:
            Array: [Simple weapons Martial weapons]

Failing one depending on `github.com/CloudyKit/jet/v6`:

    ❯ ./failure/failure
    2024/12/12 18:19:37 Executing template failed: Jet Runtime Error ("/template.jet":1):
    value {[{Name Barbarian} {Description A fierce warrior of primitive background who can
    enter a battle rage} {Proficiencies [{Armor [Light armor Medium armor Shields]}
    {Weapons [Simple weapons Martial weapons]}]}] 3 0} (type interface {}) is not rangeable

The failure happens when trying to process the value of `Proficiencies` as a range.

## Details

There's more information [in the repo](https://github.com/prantlf/jetnoranger). The template execution itself is straightforward:

    metadata := yaml.MapSlice{}
    if err := yaml.UnmarshalWithOptions(content, &metadata, yaml.UseOrderedMap()); err != nil {
      ...
    }
    wrapper := &mapWrapper{
      entries: metadata,
      len:     len(metadata),
    }
    context := &templateContext{
      Metadata: wrapper,
    }
    var buf bytes.Buffer
    if err := template.Execute(&buf, nil, context); err != nil {
      ...
    }

I unmarshal YAML input by `github.com/goccy/go-yaml` to an ordered map `yaml.MapSlice` and wrap it by a rangeable `mapWrapper`:

    type mapWrapper struct {
      entries yaml.MapSlice
      len     int
      i       int
    }

    func (m *mapWrapper) Range() (reflect.Value, reflect.Value, bool)
    func (m *mapWrapper) ProvidesIndex() bool

The input YAML is an object, which can have scalar, array and object values. The second-level object values are wrapped with `mapWrapper` too, but they aren't recognised as rangeable.

The `Range` enumerator returns the map values wrapped to `valueWrapper` to be able to recognise scalars, arrays and maps:

    type valueWrapper struct {
      Value   interface{}
      IsArray bool
      IsMap   bool
    }

The `Value` can be `string`, []interface{} or `mapWrapper`.

The first-level `mapWrapper` object is passed to the template execution as `Metadata` in the the context:

    type templateContext struct {
	    Metadata interface{}
    }

The template:

    {{ range key, val := .Metadata }}
      Key {{ key }}:
      {{ if val.IsMap }}
        {{ range k, v := val.Value }}
          Key {{ k }}:
          {{ if v.IsMap }}
            Map: {{ v.Value }}
          {{ else if v.IsArray }}
            Array: {{ v.Value }}
          {{ else }}
            Scalar: {{ v.Value }}
          {{ end }}
        {{ end }}
      {{ else if val.IsArray }}
        Array: {{ val.Value }}
      {{ else }}
        Scalar: {{ val.Value }}
      {{ end }}
    {{ end }}

The YAML input:

    Name: Barbarian
    Description: A fierce warrior of primitive background who can enter a battle rage
    Proficiencies:
      Armor:
        - Light armor
        - Medium armor
        - Shields
      Weapons:
        - Simple weapons
        - Martial weapons

**Comment by sauerbraten** [comment]
The regression seems to be in this commit: 3838f8b1234c7dd32a42bf3ec55d79f426deb03e
When accessing fields via the struct field cache, an empty interface (`interface{}` aka `any`) is not "indirected" through as before.

By the way, newer Jet versions support whitespace trimming (using `{{-` and `-}}`) to avoid the many newlines in your example's output, like this:

<details>
<summary>click to expand</summary>

```
{{- range key, val := .Metadata -}}
  Key {{ key }}:
  {{ if val.IsMap -}}
    {{- range k, v := val.Value -}}
      Key {{ k }}:
      {{ if v.IsMap -}}
        Map: {{ v.Value }}
      {{- else if v.IsArray -}}
        Array: {{ v.Value }}
      {{- else -}}
        Scalar: {{ v.Value }}
      {{- end }}
    {{ end }}
  {{- else if val.IsArray -}}
    Array: {{ val.Value }}
  {{- else -}}
    Scalar: {{ val.Value }}
  {{- end }}
{{- end -}}
```
</details>
