### ISSUE TITLE
Submit pull request with your benchmark template

### ISSUE THREAD

**Issue by SlinSo** [CloudyKit/jet#29]
Hi,

nice work!

I would like to include your template engine in my benchmark. Could your please open a pull request and submit your templates.
[goTemplateBenchmark](https://github.com/SlinSo/goTemplateBenchmark)

thanks.

**Comment by annismckenzie** [comment]
We're in the middle of the finishing touches for v2. We'll redo the benchmarks and then submit the PR. Thanks for stopping by! 👯

**Comment by annismckenzie** [comment]
SlinSo/goTemplateBenchmark#1 was merged today! This is now resolved.
