### ISSUE TITLE
Import or Extend via variable?

### ISSUE THREAD

**Issue by stevielj** [CloudyKit/jet#31]
Hi. Thanks for your great template engine! Is it possible to use a variable or function result in the extends, import, or includes statements?

**Comment by annismckenzie** [comment]
I'm not quite sure what you mean exactly. Can you whip up a quick example or some pseudo-template of what you're trying to do?

**Comment by stevielj** [comment]
It looks like this is possible with include but not import or extends. What I'm thinking about doing is importing items based on data/variables in the context. I might want to load a bit of html that's specific to a given user type, language, tenant, etc. The way I've done this in the past was to check for the existence of a sub-template, and maybe load a different sub-template if a specific version doesn't exist. 


  {{extends "layouts/application.jet"}}
  
  {{block body()}}
    <main>
    {{ include "hi_" + Language }} {{ Username }},<br/>
      This content is for you!
    </main>
  {{end}}


<b>Hello!</b>

**Comment by annismckenzie** [comment]
I see what you're trying to do. Gonna have to wait for @jhsx to chime in here but I added an example of how you could do this right now in a separate branch to the example project. Check out the branch, go into the example directory, run `go run main.go`, and point your browser to `http://localhost:8080/todo?id=example-todo-2` to see this in action.

**Comment by jhsx** [comment]
Hi @stevielj , this is not possible with extend/import for performance reasons, one way would be to use a string replace func (strings.Replace or Regex) and recompile the template or using include.

@annismckenzie why not use the include statement ? from revision 04890a1a51973132058953850e18e6e714472baa include evaluates an expression as the first parameter

**Comment by jhsx** [comment]
This is valid and cleaner
```html
{{extends "layouts/application.jet"}}

{{block documentBody()}}
  <h1>Show TODO</h1>
  <p>This uses a custom renderer by implementing the jet.Renderer interface.
  <p>
    {{ . }}
  </p> 
    This is a special snippet for the TODO {{ id }}: {{include "todos/show_"+id .}}
 {{end}}
```

**Comment by annismckenzie** [comment]
Yes but it will fail if the template cannot be found (which is what the OP is asking for).

**Comment by stevielj** [comment]
Thanks for your help. I should be able to make this work.
