### ISSUE TITLE
Strip html space

### ISSUE THREAD

**Issue by hao1118** [CloudyKit/jet#34]
{{if ...}}...{{end}} or {{...}} will leave space in the output.
go1.6+ template like {{- ...}} or {{... -}} is OK.
Thanks!

**Comment by annismckenzie** [comment]
That would indeed be nice. :)

**Comment by jhsx** [comment]
We should implement this, but i don't think the go1.6+ template will fit very well because of negative numbers, per example {{-1}}.

So, we need to choose a better operator.
```
{{: if }} .... {{ end :}}
```

**Comment by mj420** [comment]
What do you think about minifying templates on load to app? Just remove newlines, unused spaces, tabs when templates are loaded.
eg.
```
{{block menu()}}
  <ul>
    {{range .}} {* set the context appropriately *}
      <li>{{ .Text }}{{if len(.Children)}}{{yield menu() .Children}}{{end}}</li>
    {{end}}
  </ul>
{{end}}
```
result:
```
{{block menu()}}<ul>{{range .}}{* set the context appropriately *}<li>{{ .Text }}{{if len(.Children)}}{{yield menu() .Children}}{{end}}</li>{{end}}</ul>{{end}}
```
that would solve the problem, speed up template rendering and generate less response code

**Comment by annismckenzie** [comment]
That's actually a very good idea! @jhsx Would that be hard to implement?

**Comment by jhsx** [comment]
I've been thinking in ways to do this from the very beginning, the problem with this is maintain a consistent parsing state of the html inside the template.

This is very hard to implement, because jet is dynamic will be very easy to break assumptions that the minificator did in compile time when at runtime.

**Comment by japettyjohn** [comment]
I agree with @CaptainCodeman on not mixing up functionality. But doing this before the template is cached may a sufficient memory savings to do a hook for this. While compression would similarly be suitable it would incur a decompression cost at every lookup.

**Comment by annismckenzie** [comment]
I think we can defer this to a reverse proxy or some other middleware at a higher level doing this minification – closing as wontfix.
