### ISSUE TITLE
Wiki - Getting Started has bad info

### ISSUE THREAD

**Issue by andradei** [CloudyKit/jet#36]
On https://github.com/CloudyKit/jet/wiki#getting-started
The comment on the line of code that says:

`var View = jet.NewHTMLSet("./views")) // relative path to the Go file where this code is located
`

Should actually say `// relative to the current working directory from where the code is run` or something along those lines because `jet.NewHTMLSet()` doesn't traverse up the directory tree, only down (from what I tested), so stuff like `jet.NewHTMLSet("./../views")` won't work.

**Comment by annismckenzie** [comment]
Fixed, thanks for reporting it! :)
