### ISSUE TITLE
{{...}} inside a string not working

### ISSUE THREAD

**Issue by hao1118** [CloudyKit/jet#38]
{{.myvar}} is OK but "blahblah...{{.myvar}}blah..." not working, rendering stops.

**Comment by annismckenzie** [comment]
How can you be inside a string in a template? That doesn't make any sense. Can you paste a more comprehensive snippet here that shows what you mean?

Is this what you're trying to do?
```HTML
<div>
  {{ .myvar }} not inside a string

  {{ "inside a string {{.myvar }}" }} <!-- you can't nest these -->
  {{ "inside a string "+.myvar+" will work" }} <!-- but you can concatenate them -->
</div>
```

**Comment by hao1118** [comment]
sorry, it really works, I called a global variable,
 {{range .Myslice}}
<a href="{{GloableVarNotWorking}}" title="{{VarofMysliceOK}}">blah...</a>
{{end}}

**Comment by hao1118** [comment]
I try to define a local var, it works now, don't know why:
{{locale:=.User.Locale}}
{{range .tags}}
a href="{{locale}}/tag/{{.}}"
{{end}}

**Comment by annismckenzie** [comment]
The call to `t.Execute()` returns an error when there was one when rendering the template:
```go
  if err = t.Execute(&w, vars, nil); err != nil {
      // error when executing template, log it
  }
```
Can you log that error and paste it here?

I'm not really clear on what's not working – and without a failing test case I really can't do much. The go test tooling is really good, just take a look into your (vendored?) jet library and run `go test` in there. If you can provide a failing test case I have something to work with.

Also, this seems really really odd. This is like the basics of template rendering – if that wasn't working I couldn't use it in production. :)

**Comment by annismckenzie** [comment]
Come find me on Gitter: https://gitter.im/CloudyKit/jet. I'll be there all day.

**Comment by hao1118** [comment]
Thanks Daniel!
here I post the error message:
Jet Runtime Error("public/product.jet.html":0): there is no field or method "User" in string

**Some source codes:**

type UserInfo struct {
	Id       string
	Roles    string
	Username string
	Locale   string
}

type PageContext struct {
	User       UserInfo
	Url        string
	Title      string
	MetaKey    string
	MetaDesc   string
	Breadcrumb string
	Content    string
	Extra      map[string]interface{}
}

func product(ctx *fasthttp.RequestCtx, seo string) {
        user := USER(ctx)
        ...  //get doc from mongodb
        loc := doc.Locales[user.Locale]
        pc := PageContext{
		User:       user,
                Title:      loc.Name,
		...
		Extra:      make(map[string]interface{}),
	}
        ...
        pc.Extra["tags"] = loc.Tags   //[]string{...}
        Render(ctx, "public/product", ck, nil, pc)  //ck: cache key
}

template public/product.jet.html:
&lt;div class="tags"&gt;
    {{i18n(.User.Locale,"TAGS")}}: 
    {{range .Extra.tags}}
        &lt;a href="/{{.User.Locale}}/tag/{{.}}"&gt;{{.}}&lt;/a&gt;    //here emit error
    {{end}}
&lt;/div&gt;

redefine a local variable then everything OK:
&lt;div class="tags"&gt;
    {{i18n(.User.Locale,"TAGS")}}: 
    {{locale:=.User.Locale}}
    {{range .Extra.tags}}
        &lt;a href="/{{locale}}/tag/{{.}}"&gt;{{.}}&lt;/a&gt;    //no error
    {{end}}
&lt;/div&gt;

**Comment by annismckenzie** [comment]
Yes, I see what's going wrong there – sorry that I didn't see it before!

Let me explain. Let's start with this snippet:
```HTML
{{range .tags}} <!-- each loop invocation sets the scope to that one tag (string) -->
  <a href="{{.User.Locale}}/tag/{{.}}"> <!-- trying to access tag.User -->
{{end}}
```
The range is setting a new scope which becomes the new `.`. Nothing we can do about that.

Personally, I'm rarely using the context and always use the more explicit variable map – those dots are hard to read and you always have to trace where they're set (classic example: this issue you're having right now). I'd advice you to put the user into the var map. I know that some other templating engines are providing the root scope as something like `{{ $.User.Locale }}` – that's not something we're currently doing.

On a separate note: the context is supposed to be a single object you're passing to blocks or a partial when rendering a list of, say, products. The user (currently logged-in I guess?) shouldn't be in there.

**Comment by hao1118** [comment]
Actually it's not the bug of jet, I will put variables into varmap.
Thanks again! I have tried many templates such as gotemplate, jade, quicktemplate, handlebars..., only jet runs fast as well as easy to use.
