### ISSUE TITLE
Variable in block parameter

### ISSUE THREAD

**Issue by toby3d** [CloudyKit/jet#44]
### I have this
Go code:
```go
...
func theaterPage(client *gin.Context) {
	channel := client.Param("channel") // is just a string like "Left4Bot"
	view, err := views.GetTemplate("theater.tpl.html")
	if err != nil {
		return
	}
	view.Execute(client.Writer, jet.VarMap{
		"ChannelName": reflect.ValueOf(channel),
	}, nil)
}
```

My block:
```html
{{block embedPlayer(channel="toby3d", autoplay=false)}}
	<iframe src="//www.hitbox.tv/#!/embed/{{ channel }}?autoplay={{ autoplay }}" width="360" height="640" frameborder="0" allowfullscreen></iframe>
{{end}}
```

My template:
```html
{{ block body() }}
	<main>
		{{ yield embedPlayer(channel=.ChannelName, autoplay=true) }}
	</main>
{{ end }}
```

And this does not work. How can I implement a variable in a block parameter?

**Comment by jhsx** [comment]
@toby3d check the error returned in Execute (this will give you a good idea of what is not working), i think the problem is the dot in ".ChannelName", remove the dot and should work.

The dot is to access fields in the context, when accessing a global or a VarMap variable use just the variable name.

**Comment by toby3d** [comment]
> ...remove the dot and should work.
Nope. Still doesn't work.

Source code output on page:
```<main>
			</main>```

**Comment by jhsx** [comment]
Can you post the error output of Execute ?

**Comment by toby3d** [comment]
I don't have any error output. Page open fine, Gin works fine, but I can't see my block on page. :|

**Comment by jhsx** [comment]
view.Execute(...) returns an error value
```go
err = view.Execute(client.Writer, jet.VarMap{
		"ChannelName": reflect.ValueOf(channel),
	}, nil)
if err != nil { println(err.Err()) }
```

**Comment by toby3d** [comment]
Okay, I get it:
`Jet Runtime Error("theater.tpl.html":6): unresolved block "embedPlayer"!!`

**Comment by jhsx** [comment]
Is embedPlayer defined in same file or in the parent template ? if defined in other file you will need to  do a import in the head of the file {{ import "filename.tlp.html" }}.

**Comment by toby3d** [comment]
> ...Is embedPlayer defined in same file or in the parent template

My structure looks like this:
./partials/embed.tpl (blocks) => theater.tpl.html (body of page) => layout.jet.html (default head, body, footer)

I tried to do the import, but it did not help.

-----

My embed.tpl contain only one block:
```html
{{block embedPlayer(channel="toby3d", autoplay=false)}}
	<iframe src="//www.hitbox.tv/#!/embed/{{ channel }}?autoplay={{ autoplay }}" width="360" height="640" frameborder="0" allowfullscreen></iframe>
{{end}}
```

My theater.tpl.html:
```html
{{ extends "layout.jet.html" }}
{{ import "partials/embed.tlp" }}
{{ block title() }}Theater{{ end }}

{{ block body() }}
	<main>
		{{ yield embedPlayer(channel=ChannelName, autoplay=true) }}
	</main>
{{ end }}
```

And layout.jet.html:
```html
<!DOCTYPE html>
<html>
	<head>
	    <meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
	    <title>{{ yield title() }}</title>
		<link rel="stylesheet" href="/assets/tocas/tocas.min.css">
	    <link rel="stylesheet" href="/assets/style.css">
	</head>
	<body>
	    {{ yield body() }}
	    <script src="//yastatic.net/jquery/3.1.0/jquery.min.js"></script>
	    <script src="/assets/tocas/tocas.js"></script>
	    <script src="/assets/custom.js"></script>
	    {{ include "partials/analytics.tpl" }}
	</body>
</html>
```

**Comment by jhsx** [comment]
You have a typo in your import.
```html
{{ extends "layout.jet.html" }}
{{ import "partials/embed.tlp" }} <== should be embed.tpl
{{ block title() }}Theater{{ end }}

{{ block body() }}
	<main>
		{{ yield embedPlayer(channel=ChannelName, autoplay=true) }}
	</main>
{{ end }}
```

**Comment by toby3d** [comment]
Nope. Still blank page.

**Comment by jhsx** [comment]
Please replace you theaterPage with the following and post the output error message.
```go
func theaterPage(client *gin.Context) {
	channel := client.Param("channel") // is just a string like "Left4Bot"
	view, err := views.GetTemplate("theater.tpl.html")
	if err != nil {
                println(err.Err())
		return
	}
	err = view.Execute(client.Writer, jet.VarMap{
		"ChannelName": reflect.ValueOf(channel),
	}, nil)
       if err != nil {
                println(err.Err())
		return
	}
}
```

**Comment by toby3d** [comment]
If `{{ import "embed.tpl "}}`, then: `template: theater.tpl.html:2: template embed.tpl can't be loaded`

If `{{ import "partials/embed.tpl" }}` (what's right path) or if i remove `import`, then: `Jet Runtime Error("theater.tpl.html":0): there is no field or method "ChannelName" in nil`

**Comment by jhsx** [comment]
Looking by the error message now the problem is the dot in .ChannelName if you already removed stop the app and run again to reset the cached templates.

**Comment by toby3d** [comment]
And nothing. Seriously. 😐
UPD: Only then i add import block with path and remove the dot from embed block, after rebuild all works fine. Thanks!
