### ISSUE TITLE
Multiple Directory Or Template File

### ISSUE THREAD

**Issue by s4l1h** [CloudyKit/jet#46]
Possible add multiple template directory or add template file?
I don't see any options.

`var View = jet.NewHTMLSet("./templates"))`

Eg:
`View.AddDir("./modules/group/views") `
Or:
```
View.AddTemplateFile("./modules/group/views/add.html")
View.AddTemplateFile("./modules/group/views/delete.html")
View.AddTemplateFile("./modules/group/views/list.html") 
View.AddTemplateFile("./modules/group/views/update.html")
```
OR:
```
fileName:="./modules/group/views/update.html"
content,err:=ioutil.ReadFile(fileName)
if err!=nil{
    View.AddTemplate(fileName,content)
}
```

> ├── modules
│   ├── config
│   │   ├── config.go
│   │   └── init.go
│   ├── group
│   │   ├── acl.go
│   │   ├── controller.go
│   │   ├── init.go
│   │   ├── locale
│   │   │   ├── en-US.yaml
│   │   │   └── tr-TR.yaml
│   │   ├── locale.go
│   │   ├── models.go
│   │   └── views
│   │       ├── add.html
│   │       ├── delete.html
│   │       ├── list.html
│   │       └── update.html
├── templates
│   ├── a.html
│   ├── a.js
│   ├── admin
│   │   └── menu
│   │       └── index.gohtml
│   ├── default
│   │   └── layouts
│   │       └── layout.gohtml
│   ├── index.gohtml
│   └── v1
│       └── layouts
│           └── layout.tpl

**Comment by annismckenzie** [comment]
As for embedding binary data support that should be a separate issue – you may take a look at #37 which tackles this using `vfsgen`. I'm already using that in production and ship all the templates in the compiled binary. Can `go-bindata` provide access via the `http.FileSystem` interface as well?

**Comment by annismckenzie** [comment]
To add additional template paths use `View.AddPath(dir)` (see https://godoc.org/github.com/CloudyKit/jet#Set.AddPath) or just provide them when instantiating the set:

```go
  var View = jet.NewHTMLSet("./templates", "./modules/group/views")
```

(see https://godoc.org/github.com/CloudyKit/jet#NewHTMLSet)

**Comment by annismckenzie** [comment]
Did you make progress using the information I provided?

**Comment by annismckenzie** [comment]
Closing this because there's no response and the OP's question was answered.
