### ISSUE TITLE
Email templates - how to inline CSS?

### ISSUE THREAD

**Issue by VojtechVitek** [CloudyKit/jet#49]
Hey guys,
this might not be related to Jet directly but asking other experienced developers doesn't hurt.

How would you approach inlining the CSS within email templates?

Say, I have a set of Jet email templates and a common .css file. During the template execution, I'd like to be able to inline all the CSS into the HTML tags.

Is there anything in Jet that would help me do it?

Or would you suggest executing the Jet template first and then iterate on the resulting HTML with tools like https://inliner.cm/ or https://templates.mailchimp.com/resources/inline-css/ ?

Thanks for your replies

**Comment by VojtechVitek** [comment]
Just for reference:
https://github.com/aymerick/douceur
https://github.com/vanng822/go-premailer

These tools might be used on the result HTML after the Jet template is executed.

**Comment by jhsx** [comment]
@VojtechVitek We don't have anything built-in to deal with it, i would go with one of the libraries mentioned in your last comment. Depending on how complex is your template you could process the inline on load time, that will be way better than run the inlining func on the output of template every time.
