### ISSUE TITLE
Put some examples

### ISSUE THREAD

**Issue by vadimyer** [CloudyKit/jet#5]
Not quite sure how should this be used? Thanks!

P.S. I mean examples of logic connection. How can you use jet along with gin?

**Comment by jhsx** [comment]
Hi @vadimyer template syntax is can be checked in the test data, and i will put an example project in a different repo. i don't know how to use gin but i all try to make a seed project for it.

**Comment by nkev** [comment]
Is /examples/devop.yml used anywhere? I can't find code that loads it..

**Comment by jhsx** [comment]
@nkev devop.yml is an configuration file for "devop", devop works as proxy that watch for changes in the file system and execute commands for the changing files, commands are executed before the proxy complete the request. i expect to release this in the following repo https://github.com/jhsx/devop, just need some cleanup, examples how to use.

**Comment by nkev** [comment]
ok, thanks for clarifying.

**Comment by jhsx** [comment]
you're welcome.

**Comment by annismckenzie** [comment]
I updated the wiki with a getting started section and more pages covering the built-in functions, how to render templates and more information on the syntax.

That should take care of this issue.
