### ISSUE TITLE
Variable declaration then use in layout

### ISSUE THREAD

**Issue by shkim** [CloudyKit/jet#53]
I want to do something like this:

```
<!-- file: "layout.jet" -->
<!DOCTYPE html>
<html>
  <head>
    <title>{{yield title()}}</title>
  </head>
  <body>
    <div class="menu">
      <menu {{if mnu=="m1"}} class="active"{{end}}>Menu #1</menu>
      <menu {{if mnu=="m2"}} class="active"{{end}}>Menu #2</menu>
      <menu {{if mnu=="m3"}} class="active"{{end}}>Menu #3</menu>
    </div>
    {{yield body()}}
  </body>
</html>

<!-- file: "home.jet" -->
{{extends "layout.jet"}}
{{ mnu := "m1" }}
{{block title()}}My title{{end}}
{{block body()}}
  <main>
    This content will be yielded in the layout above.
  </main>
{{end}}
```

But I got runtime error message : 
Jet Runtime Error("layout.jet":8): identifier "mnu" is not available in the current scope map[]

if I declare mnu variable in layout.jet file, the page will be rendered as I expected.
but how can I set the value of mnu variable in view file?

I tried  {{ mnu := yield menuValueBlock() }} in layout file but failed.

**Comment by annismckenzie** [comment]
I'd put the navigation in a block and yield that in the body block like so:
```html
<!-- file: "_blocks.jet" -->
{{block nav(active="")}}
<div class="menu">
  <menu {{if mnu=="m1"}} class="active"{{end}}>Menu #1</menu>
  <menu {{if mnu=="m2"}} class="active"{{end}}>Menu #2</menu>
  <menu {{if mnu=="m3"}} class="active"{{end}}>Menu #3</menu>
</div>
{{end}}

<!-- file: "layout.jet" -->
{{import "_blocks.jet"}}
<!DOCTYPE html>
<html>
  <head>
    <title>{{yield title()}}</title>
  </head>
  <body>
    {{yield body()}}
  </body>
</html>

<!-- file: "home.jet" -->
{{extends "layout.jet"}}
{{ mnu := "m1" }}
{{block title()}}My title{{end}}
{{block body()}}
  {{yield nav(active=mnu)}}
  <main>
    This content will be yielded in the layout above.
  </main>
{{end}}
```

Is that a workable solution for you?

**Comment by shkim** [comment]
thanks your advice.
but practically, in view file, I declare rather just mainSection() block not full body() block.
the common html layout frame structure would be in layout.jet.

if i use the above idea, i think i should write much redundant layout html code in body() block.
because generally nav() section is not embedded in mainSection() block.
like this:

```
{{block body()}}
   <div class="left side">
      .... redundant decorative code ...
     <div blabla><div blabla2>
        {{yield nav()}}
     </div></div>
     ...
   </div>
   <div class="main center">
    ... redundant decorative code ...
    <div blabla><div blabla2>
      Unique contents of this view file (mainSection)
   </div></div>
    ....
</div>
{{end}}
```

is my expectation wrong?

**Comment by annismckenzie** [comment]
Yes and no. It really depends on how complex your navigation is going to be and if it's going to be complex then I don't really have an answer for you.

Ours is pretty static – in the sense that we use the HTTP request's URL and path (which we inject into every template instance when rendering a page) to determine which top-level nav item should be active.

Jet is just a building block. When I came to Go from Symfony2 (PHP) and Rails (Ruby) there was a ton of stuff missing that's just simply there in those frameworks. Lots of magic happens and it all just works but here you need to do a few things yourself.

**Comment by shkim** [comment]
In fact, I want to use Bootstrap Admin Template for layout:
such as https://almsaeedstudio.com/themes/AdminLTE/index2.html
The layout html is somewhat complex and long.
so i thought it is not efficient to implement blocks with the above concept.

There are many side navigation menu items, and one active item element has a special css class.
If there is another way to insert css class conditionally, in layout, i would appreciate it.

**Comment by annismckenzie** [comment]
Wow, that really is a big template and an especially big sidebar. That also goes a lot farther than simply adding CSS classes and should probably have its own controller struct class that accepts the request. Jet has some advanced concepts like a [custom renderer](https://github.com/CloudyKit/jet/wiki/Advanced#custom-renderer-with-jetrenderer). Objects implementing that interface will have their `Render` function called when doing `{{ objectImplementingRendererInterface }}` in a jet file. You create that in your controller and pass it everything it needs to know for rendering the sidebar. Still, I can't give you copy'n'pasteable code here, that's just too extensive. Maybe you'd be better off with a CMS based on Go that has primitives (like a menu for navbar, sidebars and footers) for this already?

**Comment by shkim** [comment]
Okay, thank you. I'll try the complex way later.
In my case I can set the mnu variable in Go code as a workaround.
