### ISSUE TITLE
Question about getting rendered Html

### ISSUE THREAD

**Issue by sachinwalia2k8** [CloudyKit/jet#54]
I am planning to use jet for generating Html email content. How do I read all the rendered Html into a String. All the tests I've found so far point to writing it to Http response writer.

**Comment by sachinwalia2k8** [comment]
Figured it out. If someone else looking for the same answer here is the sample code:

```
	var byteBuf bytes.Buffer
	tmpl, err := config.JetView.GetTemplate("test.jet")
	if err != nil {
		log.Println("Unexpected template err:", err.Error())
	}
	tmpl.Execute(&byteBuf, nil, nil) //read it in byte buffer
	var renderedHtml string = byteBuf.String()
	log.Print(renderedHtml) //write it to log or push it to DB etc..
	res.Write(byteBuf.Bytes()) //write it to http response object for viewing on browser
```

**Comment by annismckenzie** [comment]
And here's a library that also fits into this use case: https://github.com/matcornic/hermes.

Closing this issue though – thanks for posting back the solution! :)
