### ISSUE TITLE
Redis Caching

### ISSUE THREAD

**Issue by zet4** [CloudyKit/jet#55]
I want to cache templates in redis for an hour, but jet itself caches templates permanently, is there any way to go about this?

**Comment by jhsx** [comment]
Are you speaking about the generated html or the template bytes or the template parsed ?

**Comment by zet4** [comment]
Template parsing, I want cache to live for an hour and then re-parse them so I can swap the templates whenever at runtime without enabling development mode.

**Comment by jhsx** [comment]
This will be very hard to implement, one way would be to serialize/unserialize the Set with the gob encoder/decoder, but i think this would not bring any benefits over parsing the template bytes.

**Comment by zet4** [comment]
Yeah I ended up using redis as a lock and just reload templates from FS on expiration.

I will now close this.
