### ISSUE TITLE
Handling non existent variables in template

### ISSUE THREAD

**Issue by sachinwalia2k8** [CloudyKit/jet#56]
Some template frameworks (at least in Java) replaces non existent variables with blank values. Is it possible to do something like this in jet? 

My use case is that there is a common html snippet which renders content based on some variables.

If variables are not set it should assume those values as blank and continue executing. Right now Jet is breaking and expecting me to set those variables albeit empty everywhere.

**Comment by annismckenzie** [comment]
You may use Jet's blocks feature to accomplish this – see https://github.com/CloudyKit/jet/wiki/Jet-template-syntax#new-in-v2-local-block-variables-with-defaults-and-wrapping-at-invocation-time. Just define a block for your common HTML snippet, add the appropriate parameters that are used in that, add default values for them (all data types are possible) and you're done. I also invite you to read that whole document, there's a lot of additional information in there regarding partials, blocks, yielding, wrapping and how templates are looked up.

Does that help you?

**Comment by annismckenzie** [comment]
I gave the OP a good answer but there's no follow-up questions – closing.

**Comment by sachinwalia2k8** [comment]
@annismckenzie sorry about the lack of response. The information you provided was helpful. cheers.
