### ISSUE TITLE
ARMv7 / x32 bit support

### ISSUE THREAD

**Issue by zet4** [CloudyKit/jet#58]
When I try to build my project with Jet template engine I get an error:
```
$ GOOS=linux GOARCH=arm  go build -i -o rixvox
# github.com/CloudyKit/jet
..\..\CloudyKit\jet\default.go:56: constant 99999999999 overflows int
```

**Comment by jhsx** [comment]
Hi, thanks to report, this should be easy to fix, i will send a fix in the weekend.
