### ISSUE TITLE
Introspecting templates for variables used

### ISSUE THREAD

**Issue by willtrking** [CloudyKit/jet#59]
Hey there

Is it possible to introspect Jet templates once their parsed, or before their parsed? Ideally I'd like to be able to pull out which variables are used in a template before execution, so I can decrease lookup time by not loading unnecessary data. The use case here is per-user template execution for emails. Users have KV pairs stored in a database, and when rendering a template it'd be great if I don't have to pull them all in.

Thanks!

**Comment by jhsx** [comment]
Hi, you can walk the template tree "Template.Root".
I've been thinking about adding a visitor or walk api into a utils package, this would simplify what you are trying to accomplish.

**Comment by jhsx** [comment]
@willtrking sorry, my last response was wrong the root field in the template was not exported.

I sent some changes that address this, now Template.Root is exported and add an walk function in the utils package that will make inspecting template AST very easy, for usage examples check the test file in the utils package.

**Comment by willtrking** [comment]
@jhsx Can't thank you enough! Super useful for me

So in terms of the nodes that could hold identifiers expected from a VarMap, would that be `IdentifierNode `,  `ActionNode`, `FieldNode`? If a key in a VarMap is used in a `RangeNode`, would I get the key from the `RangeNode` or another node after it?

Thanks again!!

**Comment by jhsx** [comment]
@willtrking  You're welcome.

You will need to test for IdentifierNode's only.
```go
// this function will walk all nodes in the template ast
utils.Walk(mTemplate, utils.VisitorFunc(func(context VisitorContext, node jet.Node) {
		if node.Type() == jet.NodeIdentifier {
			collectedIdentifiers = append(collectedIdentifiers, node.String())
		}
		context.Visit(node) 
}))
```
I prefer to not include this directly into Jet, i think this functionality is a special use case and will be used rarely.

**Comment by willtrking** [comment]
Thanks again!! Working well for me right now. Finally working on this project again, and starting out with Jet templating.

One MORE question (sorry to bombard you), is there a way to check to see if the walker is currently inside of a `RangeNode`? Reason why I'm asking may just be because of my own ignorance in terms of the Jet syntax, but here goes:

When I walk through a template with `range var := varList` type syntax, the list of `NodeIdentifier`'s includes the `var` variable, a concrete example is the following template:

https://gist.github.com/willtrking/03df95169f4c477871641c0a896680a2

Walking that template gives me `userName, product, products, product, product, product` as identifiers. The duplication of `product` I'm not personally concerned about, more wondering if there's a way to exclude `product` all together. Additional note about this template, walking this will throw a null-pointer panic unless I include a `if node != nil` wrapper in my walk function. Seems like this is bubbling from [this line](https://github.com/CloudyKit/jet/blob/master/utils/visitor.go#L128), but didn't want to submit a PR as was unsure if this is expected behavior.

HOWEVER, when I walk THIS template:

https://gist.github.com/willtrking/0adc74794f50b51a67296a0160aaac09

I get `userName, products` as identifiers. In addition, walking this template will not cause a panic.

Both templates evaluate properly for me given the following `VarMap`

```
vars := make(jet.VarMap)

vars.Set("userName", "Alice and Bob")
vars.Set("product", map[string]interface{}{
	"name":  "BAD OVERRRIDE",
	"price": 50000000,
}) // Checking to ensure there's no override of `product` in the `range`
vars.Set("products", []map[string]interface{}{
	map[string]interface{}{
		"name":  "TEST PRODUCT ONE",
		"price": 100,
	},
	map[string]interface{}{
		"name":  "TEST PRODUCT EXPENSIVE",
		"price": 20000,
	},
})
```

I can definitely see why this is the case, given the two template definitions, but was just wondering if there was a way for me to detect a `{{end}}` expression, perhaps to filter out any identifiers declared in the `RangeNode`. Looking through the source, I see that the `RangeNode` is really a `BranchNode` and I can get the identifier from the attached `SetNode` (I think?), just not sure of a way to detect when I'm no longer inside the `RangeNode`. Another possible route would be for me to check if the `IdentifierNode` originated from an identifier declared in the template via `:=` or similar, but afraid I'm really out of my depth on this one.

Am I just ignorant of the Jet syntax, and in reality should be using the second template over the first?

Super HUGE thanks for your help, wouldn't have gotten this far without it. At this point this issue isn't really a blocker for me, just looking to keep my KV retrieval as clean as possible.

**Comment by jhsx** [comment]
You're welcome, glad it's worked.

Answering your first question, yes, you need to maintain the state by you self and the visitor will enter all nodes in the tree as long you call context.Visit(node).

I wrote this function please check if this is what you're looking for.
```go

var (
	localVariables    []string
	externalVariables []string
)

Walk(mTemplate, VisitorFunc(func(context VisitorContext, node jet.Node) {

	var stackState = len(localVariables) // saves the state of the local identifiers map

	switch node := node.(type) {
	case *jet.SetNode:
		if node.Let { // check if this is setting a new variable in the current scope
			for _, ident := range node.Left {
				// push local identifier
				localVariables = append(localVariables, ident.String())
			}
		}
		// continue checking nodes down the tree
		context.Visit(node)
	case *jet.IdentifierNode:

		// skip local identifiers
		for _, varName := range localVariables {
			if varName == node.Ident {
				return
			}
		}

		// skip already inserted identifiers
		for _, varName := range externalVariables {
			if varName == node.Ident {
				return
			}
		}

		// push external identifier
		externalVariables = append(externalVariables, node.Ident)
	case *jet.ActionNode:
		// continue without restore state of local identifiers map
		context.Visit(node)
	case *jet.BlockNode:

		// iterate over block parameters
		for _, param := range node.Parameters.List {
			// store block parameters in the local map
			localVariables = append(localVariables, param.Identifier)
		}

		// continue down tree
		context.Visit(node)
		// restore local identifiers map
		localVariables = localVariables[0:stackState]
	default:
		// continue down tree
		context.Visit(node)
		// restore local identifiers map
		localVariables = localVariables[0:stackState]
	}

}))
```

**Comment by jhsx** [comment]
@willtrking let's close this issue since it's worked for you.
