### ISSUE TITLE
Add debug mode that disables caching (while developing)

### ISSUE THREAD

**Issue by annismckenzie** [CloudyKit/jet#6]
It would be great to have a debug mode that disables template caching (and could also print out debug statements about template blocks found etc.) so as to not require constantly restarting/recompiling the app while developing.

Is that something you could add?

**Comment by jhsx** [comment]
Ya sure. a development mode looks to be a good idea.

**Comment by annismckenzie** [comment]
Awesome, thanks for adding it!

Enable the development mode by calling `SetDevelopmentMode(true)` on a Set or HTMLSet.
