### ISSUE TITLE
Add contributors section in the readme

### ISSUE THREAD

**Issue by jhsx** [CloudyKit/jet#60]

**Comment by annismckenzie** [comment]
I'll take care of this today.

**Comment by sauerbraten** [comment]
How detailed should this be? I would put @jhsx, @annismckenzie and myself, based on the number of commits as well as code additions and deletions: https://github.com/CloudyKit/jet/graphs/contributors

**Comment by sauerbraten** [comment]
Probably closed in 2ada4091acbbc7981ee93f5a91c33fdf539ee4c4.

**Comment by tooolbox** [comment]
Ya, I think we're good to close.
