### ISSUE TITLE
Rendering with iris (httprouter)

### ISSUE THREAD

**Issue by gaghan430** [CloudyKit/jet#61]
Hi guys, 
so sorry if I'm asking stupid question
but I really need your help, because I'm new in golang world
wondering how can I use this template engine with [iris framework](http://iris-go.com/)
or at least with [httprouter](https://github.com/julienschmidt/httprouter)

hope you want answer my question,
thanks!

**Comment by annismckenzie** [comment]
Please take a look at #51 and see whether you can adapt this for Iris? I have only briefly looked at their template engine integration points in the past and can help you if you have some code (or better yet, a gist) that shows what's a problem or not working. Can you provide us with that? What did you try and what doesn't work?

**Comment by gaghan430** [comment]
@annismckenzie it's working perfectly now!
thank you for helping me, really appreciate that.

**Comment by annismckenzie** [comment]
That's nice to hear! Can you close this issue, please?

**Comment by gaghan430** [comment]
with my pleasure!
