### ISSUE TITLE
Using globs funcs within yielded blocks

### ISSUE THREAD

**Issue by japettyjohn** [CloudyKit/jet#66]
I have a function in the var map (due to it's dependency on the request itself). It was done like this:

`vars.SetFunc("VURL", func(a jet.Arguments) reflect.Value {})`

```
html.html:

{{yield bodytemplate()}}
---

page.html:

{{extends "html.html"}}
{{import "utilities.html"}}
{{block bodytemplate()}}
{{yield body()}}
{{end}}
---

index.html:

{{extends "page.html"}}
{{block body()}}
{{yield video("id")}}
{{end}}
---

utilities.html:

{{block video(url)}}
{{video := VURL(url)}}
<video src="{{video}}">
{{end}}

```
When it is called in {{block body()}}, it works, when it is called in {{block video(url)}} it gets the following error:

`Error #01: Jet Runtime Error("utilities.html":25): identifier "VURL" is not available in the current scope map[]`

I can't tell from the docs how to propagate the context (or not overwrite by accident).

**Comment by dxvgef** [comment]
I also have this problem, how to deal with it?
