### ISSUE TITLE
Reflection?

### ISSUE THREAD

**Issue by nkev** [CloudyKit/jet#7]
Firstly, congratulations, nice work!
I had a quick skim though the code and saw reflection being used in a couple of places. Do you think performance could be optimised further without reflection?

**Comment by jhsx** [comment]
Hi @nkev, thanks.
I think reflection is fine, i tried to minimize in the maximum the allocations.

The only alternative i see to reflection would be to use unsafe, but this would make the project more hard to maintain and also would make the project impossible to run in sandboxed enviroments like appengine.
