### ISSUE TITLE
Is the word 'content' the keyword of the jet?

### ISSUE THREAD

**Issue by dxvgef** [CloudyKit/jet#71]
My Go code like this:
`vars.Set("content", &content)`
template file code like this:
`{{content.ID}}`
Output error: ...... unexpected {{content}}

I changed the template variable name from 'content' to 'content2', I can work.
Is the word 'content' the keyword of the jet?

**Comment by jhsx** [comment]
Hi, yes.

**Comment by toby3d** [comment]
Duplicate of #65

**Comment by annismckenzie** [comment]
Closing as a duplicate of #65 – I'll fix that over there.
