### ISSUE TITLE
Reloading templates in production

### ISSUE THREAD

**Issue by japettyjohn** [CloudyKit/jet#72]
I have a website using jet and it looks like unless I'm in development mode I won't have a way updating existing pages. For something like a CMS (which is what I'm working with) this is an issue.

My plan right now is to add an UnloadTemplate call which removes the old one from the cache, then the next hit on the template get reloaded as per usual. It could also be useful in the case 

Is that the right approach?

**Comment by japettyjohn** [comment]
[This is what I'm looking at](https://github.com/japettyjohn/jet/commit/a52168e2d1911f309eda148340b4807c9285ede2), will do a PR when I've done a bit more testing.

**Comment by japettyjohn** [comment]
This is working now and I've submitted it on #73.

**Comment by jhsx** [comment]
@japettyjohn a simple way to achieve this is to just create an new set. This is not the most optimized way, but i think still fine cause i think template reloading will not happen so often.

**Comment by japettyjohn** [comment]
@jhsx Agreed. 

In the meantime I reviewed what needs to reload and identified it did not need any templating inside of it, rather it was static body content which was wrapped in a template. 

As such I made a template which takes the content as a buffer and writes it out. Forgoing the template reload and avoids storing every page in memory as a "template".

**Comment by annismckenzie** [comment]
I agree with @jhsx on this one. If you really need to be able to reload templates, you should wrap the set and guard it with a mutex. While that could cause contention it's probably the least risky way and shouldn't impact performance that much if the render/reload ratio is really small. You'll probably want to separate your normal templates and the ones that need hot reloading by having two different template directories. The edge cases to support this in the core are so numerous that I really don't want us to do this.

Hope you're not mad but I'm closing this as a wontfix.
