### ISSUE TITLE
SetFunc() can't work in include template file?

### ISSUE THREAD

**Issue by dxvgef** [CloudyKit/jet#74]
I use `SetFunc("mytest", "...")` registered a template function, using `{{include "topbar.html"}}` in `index.html`, use the `{{mytest ("...")}}` in the `topbar.html` file output wrong:
`Jet Runtime Error("content/topbar.html":9): identifier “mytest” is not available in the current scope map[]`

**Comment by annismckenzie** [comment]
That seems weird. We're using functions in included templates quite extensively. At first I thought the space between `mytest` and the parentheses was to blame but I just checked locally that it works.

So you're setting that on a var map, right? It might be that these are not passed to included templates. /cc @jhsx

**Comment by dxvgef** [comment]
Yes, I use the SetFunc() method to import a custom function into the template, but it cannot execute the custom function in the template that comes in through the include.

**Comment by jhsx** [comment]
@dxvgef i can't reproduce this error, there is some code that you can show to us ?

**Comment by dxvgef** [comment]
I'm using template functions in the range code block of the template, maybe this is wrong.

**Comment by dxvgef** [comment]
Sorry, this is caused by my code error.
