### ISSUE TITLE
How to i18n?

### ISSUE THREAD

**Issue by toby3d** [CloudyKit/jet#75]
I see undocumented `ExecuteI18N` method and `Translator` interface, but i'm not sure how to use it. :c

**Comment by jhsx** [comment]
This was not implemented yet, the intent is to introduce an new tag ``` {{ msg "Key" }} default {{end}}``` and a new built in ```{{ trans("Key","Default") }}```, the Translator should be implemented out of the context of this project but we would provide an simple default implementation.

**Comment by toby3d** [comment]
Okay, but what about integrate [goi18n](github.com/nicksnyder/go-i18n/i18n)?

**Comment by jhsx** [comment]
In jet you can add the T function as a global ``` templateSet.AddGlobal("T",i18n.IdentityTfunc) ``` and use in templates ``` <h1>{{ T: "person_unread_email_count",1 }}</h1>```.
