### ISSUE TITLE
I can custom Delims?

### ISSUE THREAD

**Issue by dxvgef** [CloudyKit/jet#76]
I want change {{...}} to [[...]], how i should i do?

**Comment by xserve98** [comment]
This item does not seem to have been maintained

**Comment by xserve98** [comment]
I also have this need #68

**Comment by annismckenzie** [comment]
Sorry about the silence to both of you. Let me see whether I can get ahold of José next week. Hang tight. 😅

**Comment by annismckenzie** [comment]
@jhsx Can you make a decision about whether you ever want to support custom delimiters? If not, we should clearly state that here as well as in #68 and I'd add a section in the readme.

**Comment by dxvgef** [comment]
@annismckenzie I think it is necessary to support custom delimiters. The default delimiters conflict with the JS framework.

**Comment by jhsx** [comment]
@dxvgef @annismckenzie i am in favor of support custom delimiters, is someone interested in send a pull request ?

**Comment by annismckenzie** [comment]
Closing as a duplicate of #68. I'll take care of implementing it there.

**Comment by annismckenzie** [comment]
A PR implementing this feature is now open: #91. Anyone still in need of this and would be able to test it?
