### ISSUE TITLE
Is it possible to share variable between two templates?

### ISSUE THREAD

**Issue by abc100m** [CloudyKit/jet#77]
First thanks to this great project.

I want to share variable between two template, e.g.:
```go
	jset := jet.NewHTMLSet(".")
	a1, err := jset.Parse("a1", `{{varA1:="hello A1"}}`) //script1: define var in template1
	if err != nil {
		fmt.Println(err)
	}
	a2, err := jset.Parse("a2", `A1: {{varA1}}`) //script2: use the var in template2
	if err != nil {
		fmt.Println(err)
	}

	buf := bytes.NewBuffer(nil)
	err = a1.Execute(buf, nil, nil)
	if err != nil {
		fmt.Println(err)
	}
	err = a2.Execute(buf, nil, nil)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(buf.String())
```
output is:
```shell
Jet Runtime Error("a2":1): identifier "varA1" is not available in the current scope map[]
A1:
```

is it possible? or something else to finish this work?

**Comment by annismckenzie** [comment]
No, with the code you provided that's not possible – each template execution is independent. What you can do is `{{import "template_filename.jet"}}` the template and all the variables will be available to you in the importing template. There's also a section in the docs about the various ways to include, extend and import templates: https://github.com/CloudyKit/jet/wiki/Jet-template-syntax#extending-importing-including-and-yielding.

But maybe I don't fully understand what your use case is – what are you trying to do?

**Comment by abc100m** [comment]
Thanks for the reply.

I want to have a prepare script to define some global variables, then use those variables in another script while will be execute in a loop.  
Now I see this is not possible.

**Comment by abc100m** [comment]
I have another question.
Since in golang we can define functions and call it , e.g.:
```go
func greatJet(){
   fmt.Println("ha ha, this is a great project")
}
greatJet()
```
this will output:
```shell
ha ha, this is a great project
```

As in jet, we can use blocks. script likes:
```
{{block greatJet()}}
{{ha ha, this is a great project}}
{{end}}     //see,  block means define a function greatJet() and call it 

{{yet greatJet()}}
```
this script will output:
```shell
ha ha, this is a great project
ha ha, this is a great project
```

Note it have twice output, this is not like golang or other function calls. I would like to make block likes function define, not as "define a function and call it".

**Comment by annismckenzie** [comment]
Hmmm, that is weird. That behavior should only happen if you either define a block inside another block or if you pass it a context when defining it (so the block definition would be `{{block greatJet() someContextVariable}} your content{{end}}`). Can you check whether one of those 2 cases matches for you? I have lots of Jet templates in production and some of them define blocks at the top.

The other option would be for you to create a separate file next to your template (call it `blocks.jet` or `common.jet` or something like that) and import that at the beginning of your template via `{{import "common.jet"}}`. Blocks in imported templates are never executed and only made available for you to call via `{{yield myblock()}}`.

**Comment by abc100m** [comment]
This is the test code  (I'm not use .jet file but strings as input)
```go
//a.go
package main

import (
        "bytes"
        "fmt"
        "github.com/CloudyKit/jet"
)

func test2() {
        jset := jet.NewHTMLSet(".")
        a1, err := jset.LoadTemplate("a1", `{{block fn1()}}ha ha, this is a great project|||{{end}}{{yield fn1()}}`) //script1: define var in templat
e1
        if err != nil {
                fmt.Println(err)
        }

        buf := bytes.NewBuffer(nil)
        err = a1.Execute(buf, nil, nil)
        if err != nil {
                fmt.Println(err)
        }

        fmt.Println(buf.String())
}

func main() {
        test2()
}
```
output is:
```shell
[root@localhost testjet]# ./a
ha ha, this is a great project|||ha ha, this is a great project|||
``

**Comment by abc100m** [comment]
It seems like jset.LoadTemplate will panic if block have a parameter. 
```go
package main

import (
	"bytes"
	"fmt"

	"github.com/CloudyKit/jet"
)

func test2() {
	jset := jet.NewHTMLSet(".")
	// jset.SetDevelopmentMode(true)
	a1, err := jset.LoadTemplate("a1", `{{block xfn1(p1)}}ha ha,  this is a great project|||{{end}}{{yield xfn1("good")}}`)
	if err != nil {
		fmt.Println(err)
	}

	buf := bytes.NewBuffer(nil)
	err = a1.Execute(buf, nil, nil)
	if err != nil {
		fmt.Println(err)
	}

	fmt.Println(buf.String())
}

func main() {
	test2()
}
```
``shell
[root@localhost testjet]# ./b
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x4ed33a]

goroutine 1 [running]:
github.com/CloudyKit/jet.(*Runtime).recover(0xc4200c2200, 0xc42003dea8)
	/golang/gopath/src/github.com/CloudyKit/jet/eval.go:227 +0x137
panic(0x53b800, 0x6350a0)
	/golang/go/src/runtime/panic.go:491 +0x283
github.com/CloudyKit/jet.(*Runtime).evalPrimaryExpressionGroup(0xc4200c2200, 0x0, 0x0, 0x0, 0xc4200783c0, 0xc420021400)
	/golang/gopath/src/github.com/CloudyKit/jet/eval.go:553 +0x3a
github.com/CloudyKit/jet.(*Runtime).executeYieldBlock(0xc4200c2200, 0xc4200c0120, 0xc4200c2100, 0xc4200c2100, 0x0, 0x0, 0x0)
	/golang/gopath/src/github.com/CloudyKit/jet/eval.go:318 +0x176
github.com/CloudyKit/jet.(*Runtime).executeList(0xc4200c2200, 0xc4200c20c0)
	/golang/gopath/src/github.com/CloudyKit/jet/eval.go:504 +0x880
github.com/CloudyKit/jet.(*Template).ExecuteI18N(0xc4200c4000, 0x0, 0x0, 0x6251e0, 0xc4200c8000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/golang/gopath/src/github.com/CloudyKit/jet/template.go:401 +0x176
github.com/CloudyKit/jet.(*Template).Execute(0xc4200c4000, 0x6251e0, 0xc4200c8000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/golang/gopath/src/github.com/CloudyKit/jet/template.go:374 +0x79
main.test2()
	/root/go/testjet/b.go:19 +0x17a
main.main()
	/root/go/testjet/b.go:28 +0x20
```

**Comment by abc100m** [comment]
Okay, maybe blocks must used  in a .jet file.  Now I'm going to comment some code in "eval.go" to make my test case work
