### ISSUE TITLE
How render raw HTML?

### ISSUE THREAD

**Issue by Konboi** [CloudyKit/jet#8]
jet is very nice so I will use jet on my product.
I try render raw html defined template.HTML but render escaped html. 

![image](https://cloud.githubusercontent.com/assets/536667/15389542/73733190-1df2-11e6-96d8-e418ecae7e13.png)

source: https://github.com/CloudyKit/jet/compare/master...Konboi:master

**Comment by jhsx** [comment]
Hi @Konboi, you can use the unsafe writer ``` {{ unsafe: .Content }} or  {{ .Content |unsafe }}  ```

**Comment by Konboi** [comment]
Thank you @jhsx ! I can render raw HTML used by `{{ unsafe: .Content }}`.

**Comment by jhsx** [comment]
You're welcome.
