### ISSUE TITLE
For-loop or range between some ints

### ISSUE THREAD

**Issue by akuma06** [CloudyKit/jet#81]
Hi!

I wanted to range over a particular set of ints (for-loop like behavior) but I don't seem to see it supported in jet wiki.

Example: 
```
{{ startInt, endInt := getNavRange(context) }}
{{ range i := startInt...endInt }}
<a href="?page={{i}}">Page {{i}}</a>
{{ end }} 
```

I know there is the work around to create a slice of ints and range over it, but it's less efficient (variable allocations, unnecessary slice, ...). So I would like to know if it's supported but not documented.

**Comment by jhsx** [comment]
Hi, we can do this by adding a built in function between(start,end) this function only need to return a Ranger value, and we can do this very optimized.
```go
// Ranger a value implementing a ranger interface is able to iterate on his value
// and can be used directly in a range statement
type Ranger interface {
	Range() (reflect.Value, reflect.Value, bool)
}
```

**Comment by jhsx** [comment]
```go

// this is an example implemetation of the idea
func init() {
    defaultVariables["between"]=reflect.ValueOf(Func(func(a Arguments) reflect.Value {
          a.Require(1,3)
          // we can use sync.Pool here
          stepper := &intStepper{}
          //... set the paramenters based on the number of arguments
          return reflect.ValueOf(stepper)
    }))
}

type intStepper struct {
     max,step,counter int
}

func (r *IntStepper) Range() (index reflect.Value, value reflect.Value, end bool) {
    // increment the counter
     r.counter += r.step 
    // skip one allocation by using indirection to the field value
    value = reflect.ValueOf(&r.counter).Elem()
    // check if this is the last item
    bool = r.current+r.step > r.max 
    // if we are using sync.Pool we can put the value back to the 
   return
}

```

**Comment by jhsx** [comment]
Ok, glad it's helped.
Yes, i think that function would be useful also, let's add that soon.

**Comment by annismckenzie** [comment]
This seems easy enough to add – but I'm not sure whether we can add it to the defaults or make it built-in. Jet already quite a few reserved words (see #65) and I don't want to grow that list. Adding it as a default would also bump the major to v3 because it might break templates that are already out there.

**Comment by akuma06** [comment]
It seems to me to be quite helpful when you have a huge array and you only want a slice of it in your storage. In my project, I'm using it for pages navigation in navigation.jet.html helper. Every navigable object implements a Navigation interface which is used to know the range over which we build the block links.

If it seems adding it would lead to too much reserved words, you can just leave the issue with the solution.

**Comment by ryanlath** [comment]
I also desire a simple built in "for" function.  Also, for pagination.  I had trouble with the above examples, so here's mine for future reference.  Only weirdness: "1" gets converted to a float64?

Go code:
```
type jetIntStepper struct {
	count, max int
}

func (r *jetIntStepper) Range() (index reflect.Value, value reflect.Value, end bool) {
	value = reflect.ValueOf(r.count)
	end = r.count > r.max 
	r.count++
	return
}

func main() {

view.AddGlobalFunc("for", func(a jet.Arguments) reflect.Value {
	a.RequireNumOfArguments("for", 2, 2)

	s := &jetIntStepper{
		count: int(a.Get(0).Interface().(float64)),
		max: a.Get(1).Interface().(int),
	}	

	return reflect.ValueOf(s)
})
```
Jet template: (pages is an int)
```
{{ range i := for(1, pages) }}
```

**Comment by sauerbraten** [comment]
I agree a built-in ranger would be useful for this. I wrote one for our project that uses jet and called it "ints", so you would write for example `{{ range i := ints(0, upper) }}`. I like this more than "for" or "between".

PR incoming!
