### ISSUE TITLE
Allow piping first argument to function call with parentheses syntax

### ISSUE THREAD

**Issue by mvrhov** [CloudyKit/jet#82]
Pipelining parameters  passing is confusing/inconsistent.
I'm wondering why the Parameters can't be passed as you'd call the function e.g  `|function("param1", "param2")` instead of `|function: "param1", "param2"`

This get's confusing especially if you create a function date, which returns time.Time if called without parameters and a formatted time if called with parameters.
e.g
`{{date()|date:"2006"}}` would be more readable as `{{date()|date("2006")}}`

**Comment by tooolbox** [comment]
Agreed on this point.  I actually wasn't able to divine from the docs that you called functions in a pipeline using the colon syntax; I thought that was only for the special escaper function.

**Comment by sauerbraten** [comment]
I agree that this is an inconsistency. I documented it in some more detail here: https://github.com/CloudyKit/jet/blob/master/docs/syntax.md#combining-syntaxes

I'll try to make this work the intuitive way soon. (Yet another breaking change, though.)

**Comment by mvrhov** [comment]
The title is confusing now.. What would be consistent is this: {{ function1()|function2(param1, param2)|func3(p1,p2,p3,p4|.....)}} the title says only the first one.

**Comment by sauerbraten** [comment]
No, the title says if you have a function foo that takes two arguments, a and b, it should be okay to write `a | foo(b)`, just like you already can with prefix syntax: `a | foo: b` works fine.

This enables what you want, since the parentheses syntax will work in every position in the pipeline, not just the first.

**Comment by tooolbox** [comment]
@sauerbraten thanks for cleaning up the docs :)  Great to be handling issues from 2 years ago!

Not fully serious about this, but would be kinda cool to do something like [Gleam's function capture](https://gleam.run/tour/functions.html#function-capturing) where you can specify what position you want the argument in, so like `{{ foo()|bar(_, param2, param3)|baz(param1, _, param3) }}`  (Gleam probably took that from somewhere, but that's just where I've seen it recently.)

**Comment by sauerbraten** [comment]
@tooolbox that's really cool! Pipelining as currently implemented would still be supported, but it gives more flexibility and opens pipeline syntax to a lot more functions, I like it a lot. I opened https://github.com/CloudyKit/jet/issues/162 for that as it's a request for a different feature.
