### ISSUE TITLE
Google App engine with go root 1.6 gives error when we use extends

### ISSUE THREAD

**Issue by mchampaneri** [CloudyKit/jet#87]
When i tried to extend template it generated panic with this output

net/http.(*conn).serve.func1(0xc0823be000)
	C:/go_appengine/goroot-1.6/src/net/http/server.go:1389 +0xc8
panic(0xc6ea00, 0xc082006060)
	C:/go_appengine/goroot-1.6/src/runtime/panic.go:443 +0x4f7

github.com/CloudyKit/jet.(*Template).String(0xc0823c02a0, 0x0, 0x0)
	C:/Code/src/github.com/CloudyKit/jet/template.go:319 +0x65

main61784.View(0x5800058, 0xc0823d2000, 0xc0823c00e0, 0x0, 0x0, 0xe678f0, 0x15)
	utils.go:54 +0x2b9
main61784.Categories(0x5800058, 0xc0823d2000, 0xc0823c00e0)
	categories.go:9 +0x5d
net/http.HandlerFunc.ServeHTTP(0xf79840, 0x5800058, 0xc0823d2000, 0xc0823c00e0)
	C:/go_appengine/goroot-1.6/src/net/http/server.go:1618 +0x41
net/http.(*ServeMux).ServeHTTP(0xc0820665d0, 0x5800058, 0xc0823d2000, 0xc0823c00e0)
	C:/go_appengine/goroot-1.6/src/net/http/server.go:1910 +0x184
appengine_internal.handleFilteredHTTP(0x5800058, 0xc0823d2000, 0xc0823c00e0)
	C:/go_appengine/goroot-1.6/src/appengine_internal/api_dev.go:105 +0x453
net/http.HandlerFunc.ServeHTTP(0xf77dc8, 0x5800058, 0xc0823d2000, 0xc0823c00e0)
	C:/go_appengine/goroot-1.6/src/net/http/server.go:1618 +0x41
net/http.serverHandler.ServeHTTP(0xc0823b2000, 0x5800058, 0xc0823d2000, 0xc0823c00e0)
	C:/go_appengine/goroot-1.6/src/net/http/server.go:2081 +0x1a5
net/http.(*conn).serve(0xc0823be000)
	C:/go_appengine/goroot-1.6/src/net/http/server.go:1472 +0xf35
created by net/http.(*Server).Serve
	C:/go_appengine/goroot-1.6/src/net/http/server.go:2137 +0x455

**Comment by annismckenzie** [comment]
I'm sorry that you're having a bad experience. That stacktrace though doesn't tell me a lot. Here's a couple questions:
1. Go 1.6, huh? That's pretty old. I have never used Google App Engine but the docs say 1.8 is also available on GAE.
2. What gives you the impression that it's just the jet library? Does it work on your local machine?
3. Do templates in general work? Did you try with a simple template first? I'd need to see some code.

Going back to that stacktrace: just `github.com/CloudyKit/jet.(*Template).String()`? Yeah, I really need to see some code, this looks iffy.

It'd be best if you took a look into running one of the examples (see https://github.com/CloudyKit/jet#running-the-example-application) to see whether those work. I have never used GAE and I can't help you with that. Their standard environment looks really restrictive.

**Comment by mchampaneri** [comment]
Daniel ,

Thanks for reply

I am using it in my non gae projects and it working fine.

I am using go 1.8 for gae

I would like to know what further details you need.

**Comment by mchampaneri** [comment]
It generates panic when I try to extend. Otherwise it works

**Comment by annismckenzie** [comment]
Yeah, that doesn't really help clear things up with regards to that panic. If the rest is working then I don't see a reason that just that fails. We've been using Jet in production for 2 years now so it's very unlikely that it's just this single feature failing. Does the template you're extending from work on its own?

May I remind you that I'm not here to go on a fishing expedition – without some clearly structured explanations of what you tried, what works, what doesn't (you know, dev skills?) I can't really help you.

**Comment by mchampaneri** [comment]
@annismckenzie ,
There was a problem in layout i was try to extend. 
There is no problem in Jet. 
**It works fine with GAE  go-root 1.6 as well GAE go-root 1.8** 
But thanks for reply and sorry for trouble
