### ISSUE TITLE
Revamp Documentation

### ISSUE THREAD

**Issue by tooolbox** [CloudyKit/jet#92]
While the Jet Wiki here on GitHub has some useful information and examples, it is not easy to use as a reference document.  I propose this gets cleaned up!

1. In a Godoc, all objects and methods are laid out in a row with the exact signatures, with an index to find what you need.  With Jet's wiki, the important syntax examples or function names are buried in paragraphs of tutorial-style explanation.
2. The titles of each page are not clearly representative of their content.  For example, "Advanced" specifically contains interfaces you can implement to increase speed or customize rendering output.  When answering the question "What's that piece of syntax?" the answer may be in the "Expressions" page or maybe the "Jet template syntax" page, or maybe some other page entirely.
3. Some commands do not have precisely defined behavior, but are only explained through examples.  The best example of this is `yield`.
4. The documentation is sprinkled with "new in v2".  Now that v2 has been out for some time and is likely the standard, this commentary could be removed.

I would love to be able to open a PR on the Wiki, but GitHub doesn't seem to support that 😞

**Comment by annismckenzie** [comment]
Hey there and welcome! It’s awesome that you want to help! \o/

You can clone the wiki in your fork and we can see the differences locally. I’d then be able to push the changes or even add you as a collaborator so you could do it yourself. Let’s talk soon.

**Comment by tooolbox** [comment]
So I cloned the wiki in my fork: https://github.com/tooolbox/jet/wiki

Can you see differences or anything?  From searching the interwebs, it appears that GH's wiki fork/PR mechanisms have ebbed and flowed over the years, so it might be different (read: not work at all) from the last time you used it.

Anyway, I made some radical changes!  Haven't done the section on Blocks and Yields yet, and it still needs some editorial work, but the pieces are mostly rearranged how I was thinking.

Let me know your feedback at your earlier convenience, neh?

**Comment by annismckenzie** [comment]
I read through the whole thing but also cloned your version locally so I can look at the diff. I'll do so at my earliest convenience (likely this evening). 😬 Very nice work! I'm thinking about just dropping the wiki pages into a docs folder in this repository and using the GitHub Pages feature. That would make PRs for docs possible as well as allow feature PRs to include the documentation as well. WDYT?

**Comment by tooolbox** [comment]
Great, glad you like it!

I think using GitHub Pages is a great idea actually, and your point about PRs including docs changes is excellent.

In the next day or two I should be able to finish the Block/Yield section.  Maybe you want to do the GH Pages move first, so I can open a PR?  Your choice, I'm fine either way.

**Comment by annismckenzie** [comment]
Actually, you're right, I should move it now and then you can just copy your changes into that docs folder and open a PR. With GitHub's Markdown preview in PRs we can more easily see what changes and discuss inline.

**Comment by tooolbox** [comment]
Great!  Let me know when the move is done and we'll go from there :)

**Comment by annismckenzie** [comment]
Could you go ahead in the meantime? I did play around with GitHub Pages and Jekyll and trying to find a theme I can use via the `remote_theme` feature but I'm not there yet… I also don't want to break the momentum. I'll try to have something to look at in my fork by next week. 🤞

**Comment by tooolbox** [comment]
Sure :)

Okay, I finished revamping it.  Check it out and if you like it you can pull it in, however you do that.

Link, again: https://github.com/tooolbox/jet/wiki

**Comment by annismckenzie** [comment]
Alright, your changes are live! :tada: Very nice work, thank you! I especially like https://github.com/CloudyKit/jet/wiki/3.-Jet-template-syntax which is so much easier to digest and the structure is awesome. I've read through it again and there were only a few minor issues which I fixed.
I still want to move to GitHub Pages but that'll take some time.

So, do we close this issue?

**Comment by tooolbox** [comment]
Awesome!   @annismckenzie we are good to go now, thanks for fixing those things I missed.
