### ISSUE TITLE
Is there currently a way to escape the default delimiters?

### ISSUE THREAD

**Issue by RichyHBM** [CloudyKit/jet#98]
I'm aware that custom delimiters are in the works, personally I prefer using the golang conventions of {{ }}, however I am also using Vue which uses {{ }} for its variables.

Is there currently an easy way to escape the {{ }} characters? I tried with \{{ but that didn't seem to work, at the moment I am having to use {{ "{{ vueVariable }}" | unsafe }}

**Comment by annismckenzie** [comment]
Welcome! We currently have #91 open which adds custom delimiters. Can you switch over to my fork and that branch `68-allow-custom-delimiters` and see if that would work for you?

**Comment by annismckenzie** [comment]
Yes, the custom delimiters PR (now #93) will be merged later today so you can give it a try.
